### ISSUE TITLE
Guards in neutral cities don't attack players flagged for PvP

### ISSUE THREAD

**Issue by Desparto** [SunstriderEmu/BugTracker#1087]
**Description:**

Guards should attack anyone who instigates pvp within range of them.

**Current behaviour:**

CHANGEME Tell us what happens.
Guards do nothing when pvp is occurring by them.

**Expected behaviour:**

Guards should attack anyone instigating pvp

**Steps to reproduce the problem:**

CHANGEME
1. Step 1 Attack someone of the opposite faction in the middle of Area 52. 
2. Step 2 Watch as the guards do nothing.

**rev. hash/commit:** 10931

**Comment by Jerrythemagicdog** [comment]
Late but thanks!
To dev:
It's actually every guard with "guard_contested" script - it's just an empty script currently.

**Comment by networm555** [comment]
1.They should have patrol route
2.They should use dismountig blas asap as mark is on the player.
3. They should be much stronger. Wrong  stats.
4. Should not be possible ti kite them far.(home and target pathing is a mess)
5. There should be not a single spot to land free close to the cities.
People judje about private server entering a small city to see scripting and patrols. Server is an open book in those places. If you try to sell stuff and not cleaning showcase glass then who are you?
If this is moneygrab aka Unwell? Because from what iv seen it is.

**Comment by kelno** [comment]
Thank you for reporting some bugs here. As an aside, this is not the place for those kind of opinionated discussions, please use this place is for bug reports only. If you wanna tell how people will judge a whole core based on guards scripts you should use Discord instead.

**Comment by Photosynthh** [comment]
Guards in neutral cities don't attack players flagged for PvP still happening in area 52

**Comment by kelno** [comment]
Fixed since
