### ISSUE TITLE
Druid's Swipe abaility's AoE appears to be very small

### ISSUE THREAD

**Issue by Kaziner** [SunstriderEmu/BugTracker#1099]
**Description:**

Swipes AoE cone is very small

**Expected behaviour:**

When 3 mobs fan out infront of the tank when I cast swipe at the middle mob it should hit all 3 of them; at the moment it only hits the middle mob

**Steps to reproduce the problem:**

CHANGEME
1.Pull 3 mobs; let them fan infront of you
2. Cast swipe on the middle one and not it doesnt hit the other 2

Be very specific here! Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

**rev. hash/commit:** 

CHANGEME
Do a `.server info` in game and copy/screenshot the first line.  
For example: `Sunstrider rev. 10455 2019-01-09 11:31:41 +0100 (my branch) (Win64, RelWithDebInfo, Static) (worldserver)`

**Comment by mrqiksta** [comment]
I have observed this as well, nothing definite but range of swipe seems smaller than that of the vanilla core.

**Comment by Kaziner** [comment]
Unsure if a change has occurred but from further testing swipe feels correct in its hit box

**Comment by kelno** [comment]
No changes there

**Comment by Kaziner** [comment]
![swipe](https://user-images.githubusercontent.com/45530324/57564326-7cd09a80-73ed-11e9-99c5-313c9fe37775.png)

Swipe's aoe is definitely not working correctly, As seen in screenshot two mobs standing right next to eachother does not cause the swipe to hit the 2nd mob

**Comment by Orcfootstool** [comment]
- I've got a few examples. Should have recorded the combat text, but basically these were low lvl mobs that I one hit with swipe. The mobs and myself were stationary.
![swipe1](https://user-images.githubusercontent.com/48857734/57571913-4c254b00-7457-11e9-8a3b-e517fd79afc6.png)









- Here is an example of swipe not working correctly, it seems mobs around this size and larger cause swipe to not hit targets that appear to be close and should be getting hit. When tanking multiple mobs like this they also constantly shift position which compounds this issue. The 2nd pic shows swipe hitting all 3 targets once I moved the middle mob between the other two.
![swipe2](https://user-images.githubusercontent.com/48857734/57572046-12edda80-7459-11e9-9be0-875b98bc4bbe.png)
![swipe3](https://user-images.githubusercontent.com/48857734/57572051-1aad7f00-7459-11e9-92ff-d70e5befde7a.png)




- Here shows a similar situation, except as these mobs are larger swipe becomes more unreliable hitting only the middle target then hitting only two targets once the middle mob is pulled in line between the other two.
![swipe4](https://user-images.githubusercontent.com/48857734/57572169-1170e200-745a-11e9-8265-35f291eba194.png)
![swipe5](https://user-images.githubusercontent.com/48857734/57572172-1766c300-745a-11e9-9b12-e47f4584d141.png)


Also wanted to add, mobs like clefthoofs behave differently in terms of not repositioning themselves when tanking multiple clefthoofs. No idea if this is normal behaviour but it for example makes it much easier to stack them up on top of each other which is needed otherwise swipe is completely useless and will only hit 1 clefthoof unless they are as mentioned stacked right on top of each other.

**Comment by giveusmezpls** [comment]
This also appears to affect the warrior's cleave ability hinting that it might not be spell specific.

**Comment by Kaziner** [comment]
Unsure how helpful this is but after some testing it feels like the hitbox for swipe is shaped like a cone and mobs (particularly bigger model ones) get too close to the bear and get outside the cone. Pic below to explain. The red circles (mobs) are getting too close and the swipe is missing them; when fighting if they are further away swipe seems to work better but its difficult to keep them away as their natural resting position to very close. 

![swipe](https://user-images.githubusercontent.com/45530324/57598483-c14b6a00-7596-11e9-88d7-6d17edaa1ccb.PNG)

**Comment by kelno** [comment]
Updated with 11440 (or a bit before)

**Comment by Jerrythemagicdog** [comment]
fixed
