### ISSUE TITLE
Intercepts and Charges don't ignore effects like Frost Nova

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1344]
**Describe the bug**
The warrior is affected by Frost Novas , roots and all disables while on the path .

**To Reproduce**
Scenario 1:
1. Be a Mage with Frost Nova (122) 
2. Have player X intercept player Y
3. While player X is mid intercept, Frost Nova him as the Mage
4. Player X gets rooted in place

Both of those are apparently incorrect, need research or some sort of general logic to see what's right or wrong here.

**Comment by kelno** [comment]
Scenario 2: smells like a lot of spell batching going on

**Comment by maingaming** [comment]
I know that Hunters hate it but Warriors ignoring traps and trap effects (slow) during Charge/Intercept is working as intended in Vanilla/Classic and TBC.

It's rough to find proof as you have to skim through old Warrior/Hunter PvP videos and find that one special situation but I found at least one from Fylla's 2nd PvP video.

Warrior ignores slow effect:
https://youtu.be/cIG7hloWVcQ?t=134

Warrior charges over trap and trap triggers **after** that because he's still within trap range:
https://youtu.be/cIG7hloWVcQ?t=574

**Comment by Jerrythemagicdog** [comment]
Indeed, the trap seems to be intended, per comment in the core
> From 2.1.0 Feral Charge ignored traps, from 2.3.0 Intercept and Charge started to do so too

Slows, roots and stuns applied during the charge should not have immediate effect either on the charge caster (the effect should be applied but the charge should finish).

**Comment by Jerrythemagicdog** [comment]
Retail (Hoodrych gets stunned mid charge)
https://www.youtube.com/watch?v=-41Dgo6auCA&feature=youtu.be&t=144

**Comment by Jerrythemagicdog** [comment]
Still a thing in WotLK: 
https://youtu.be/9Riu2cAujPw?t=826
