### ISSUE TITLE
Combat bug issues (never leaving combat or getting put in combat state)

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1353]
**Describe the bug**
As in the title.

Some clips: 
https://clips.twitch.tv/FlirtyEsteemedPterodactylSpicyBoy -> pov priest doesn't leave combat
https://clips.twitch.tv/BovineCallousRaccoonChefFrank -> enemy rogue doesn't leave combat
Enemy rogue and pov priest leave combat at the same time.
https://clips.twitch.tv/AlertCloudyElephantBuddhaBar

**Comment by kelno** [comment]
Fixed

**Comment by kelno** [comment]
The issue is about inheriting combat states when casting a friendly spell assisting an ally. First video:

- T5: Priest cast shield on friendly rogue. He inherists combat states from his friend and gets a new combat for 6 seconds with enemy rogue.
- T11: Just before combat priest<->enemy rogue expires, the enemy druid casts lifebloom stack2. He inherits combat from his friend, and so creates a new combat ref for 6s with the player priest.
