### ISSUE TITLE
[Mage]Blink under water

### ISSUE THREAD

**Issue by ghost** [SunstriderEmu/BugTracker#1443]
**Bug description**
1) Mid-air blink when close to the ground just resets the fall.
2) Mid-air blink when terrain is in range horizontally same as 1).
3) Unable to change fall direction (?)

**Expected behavior**
1) should bring the mage to the ground and then forward if any distance remains.
claims that max distance should be 40 yards: https://github.com/Atlantiss/NetherwingBugtracker/issues/3401
https://youtu.be/k-27m_jjojg?t=47
https://youtu.be/0Tr4vjhawQc?t=188
https://youtu.be/0Tr4vjhawQc?t=432
https://youtu.be/eiC7fX07cGE?t=498

2) https://youtu.be/7cTLynfz8Zk?t=88
https://youtu.be/tK3onrwublo?t=1254
https://youtu.be/tK3onrwublo?t=1510
https://youtu.be/tK3onrwublo?t=1534

3) Nost claim it should be possible to change fall direction https://youtu.be/Ny2Hogb_k98?t=123 (worth looking into)

Sunstrider rev. 12418 (a377cdffdc5d) 2019-09-24 19:33:38 +0200 (dev branch) (Unix, Debug, Static)

**Comment by Jerrythemagicdog** [comment]
Some of those are intentional because of arena implications. 
When the mage isn't close to the ground it will not bring him close to the ground unless the distance is very small. Outside of: https://github.com/SunstriderEmu/BugTracker/issues/1352 we are satisfied with how Blink works and it's very intuitive and consistent for the players from the feedback we've received.

**Comment by earthworm-jim** [comment]
Yikes. It's broken in almost every way possible (even underwater). Not sure who satisfied with that, but you'll almost certainly get a lot of Blink reports on release (assuming server gains some traction). Just my two cents, after playing mage for ~5 years on tbc. I'm curious about these arena implications (not into arena myself).

**Comment by Jerrythemagicdog** [comment]
The arena implications are as follows:
1. Blinking from pillars to the bridge on Blade's Edge Arena would make certain team compositions too strong and allow mages to control the game with no trade off.
2. Blink doesn't reset your fall if you are in fact close to the ground, it only resets your fall if you are far from the ground (for example jumping off the bridge on Blade's Edge Arena is considered far, while jumping off the tomb on Ruins of Lordaeron is not close and doesn't reset your fall but allows you to blink in any direction). That also concerns fall direction.

If you have better ideas of how to make this spell working reliably and consistently in situations where those factors matter, while at the same time not making it overpowered and changing the class completely we can probably improve on the current implementation. 

As far as Blinking in the open world on uneven surfaces goes that is not considered a priority as it would be impossible to translate those rules into the Arena and Battlegrounds (keeping consistency in mind). 
The purpose of reducing your fall damage still works and if you use it close to a flat surface that you're about to land then you can change your fall orientation with no issues.

**Comment by earthworm-jim** [comment]
The way it works now, while falling you have to almost hit the ground before blink and the remaining distance is not used to bring the mage forward (so it's no different than a simple fall reset). That's quite a nerf opposed to 40- yards from the ground and forward movement. As for arena, would a good example be: Mage blinks from a pillar to start of the bridge and his melee opponent has to run around to reach him?

**Comment by Jerrythemagicdog** [comment]
> Mage blinks from a pillar to start of the bridge and his melee opponent has to run around to reach him?

You can currently blink from the pillars if you position and angle yourself correctly (that means there is a possible path from the pillar, through the rope to the bridge). 
I'm not sure if I'm expressing myself clear enough, but the problem that we tried to solve with the current implementation is how to make Mage not broken in Arena (Blade's Edge specifically) so that he can not Blink from the pillars to the bridge freely while keeping in mind the way Mage is played in Arena. 
Based on the feedback from PvP players which are impacted by mechanics like these the most we did OK. 
As for fall direction not being controllable when at higher altitudes that sounds completely fair and reasonable (again, keeping Arena in mind, unless we would want to use separate rules for the world and arenas). 
As much as the game is full of quirky, fun things like Blinking around and exploring the world (still possible), we want to provide an experience where the game behaves in a consistent and expected manner.
I'd be curious to know if you feel like any of this is unreasonable or impacting the game in a negative way.

**Comment by earthworm-jim** [comment]
1. and 2. have considerable impact in both pve and pvp.
couple examples:
1. pve: there are multiple fights where players get tossed high up in the air. mage can blink and continue to dps instead of losing 5+ seconds. pvp: a mage is being chased by an enemy as he jumps off LM in AB. he's out of feathers. he uses blink 30-40y (or closer for that forward push, since falling is fast) from the ground to gain some distance and escape.
2. pve: kiting mobs by blinking from one platform to another (similar to how hunters use fd and pet, although not as good), exploration. pvp: trick demostrated in the op is one good example.

Keep in mind that arena pop is a small percentage of total tbc playerbase. Idk if one arena map is good enough reason to nerf blink like that but i'm probably not understanding the consequences, since i don't play it. Hopefully other mages will join in and share their opinion on this.

**Comment by Jerrythemagicdog** [comment]
1. Currently still possible if used at the right time (minus the bonus distance) - having to press your button at the right time seems good.
2. Cool trick, perhaps still possible in WSG for us, have you tried?

"Arena population is a small population of the player base" - that doesn't automatically mean we should disregard everything they say or balance the game around that if this game is to ever be alive again. 

I don't mind discussing these issues but this is definitely not
>  Yikes. It's broken in almost every way possible

There is definitely an issue with Blinking under water.

**Comment by Jerrythemagicdog** [comment]
Closed in https://github.com/SunstriderEmu/BugTracker/issues/1592
