### ISSUE TITLE
School interrupts don't affect procs

### ISSUE THREAD

**Issue by ramadansteve** [SunstriderEmu/BugTracker#1457]
the proccs of these spells should be considered regular casts, albeit instant and free of cost.
meaning if your according school of magic is locked they should be incapable of going off/proccing.
example: im a druid and i have nature's grasp buff (improved so its 100% procc chance) up and i cast cyclone. rogue kicks me on cast and locks my nature school for 5 seconds and simultaneously deals damage to me thus proccing nature's grasp and it goes off leaving him rooted. 
same scenario with PoM up on priest getting locked on holy school

by the way, if im casting entangling roots with grasp up and i get kicked on cast, grasp doesn't do anything and just gets cancelled, which is the expected behaviour.

**Comment by Jerrythemagicdog** [comment]
I can't tell if that's the expected behaviour or actually a bug or an issue. 
I'm trying to find information confirming this behavior or an issue made raised by some other project with no results so far. 
I'd be curious to see why exactly it works this way currently for us (Grasp doesn't proc when Entangling Roots are interrupted).

**Comment by ramadansteve** [comment]
https://youtu.be/qNmGY572Jvg?t=470
so i guess it's not blizzlike, but i would still argue it's not a bad change

**Comment by Jerrythemagicdog** [comment]
Okay, we can consider it. Closing for now.
