### ISSUE TITLE
[Mage] Frost Nova has wrong stacking rules with Frostbite

### ISSUE THREAD

**Issue by sposobniy** [SunstriderEmu/BugTracker#1464]
Problem :  

1) Wrong coefficient  bonus of spell power  (higher  then should be)

2) Frostbite debuff is not getting replaced by frost nova or pet nova 

https://imgur.com/J66QAvG 

How it should work :  
1) Frost Nova should have  13.57% bonus spd 

https://wowwiki.fandom.com/wiki/Spell_power_coefficient?oldid=1549176 

2)  If frostbite procs while frost nova is active it wont take any effect as described here
http://wowwiki.wikia.com/wiki/Frostbite_(mage_talent)?direction=prev&oldid=1631922 

https://youtu.be/hDBIyF0O9bE?t=4m54s
https://youtu.be/evY1Q9KdXfM?t=1m49s
https://youtu.be/dxQvIEVPOO8?t=2m38s 

Rogue gets frostbite proc, and its replaced by frost nova from mage

**Comment by Jerrythemagicdog** [comment]
Thanks for the research.
1. Fixed in 12440
2. Currently we allow overriding your own spells always in every case so if we were to "fix" Frostbite it would just override Frost Nova. This will require us to make a general rule regarding procs and stronger effects that we could use. Seeing as this is not an important issue and actually a big buff to mages (when we implement it correctly) I won't add it for now.

**Comment by Jerrythemagicdog** [comment]
Moved second part to: https://github.com/SunstriderEmu/BugTracker/issues/1464

**Comment by kelno** [comment]
Reopening this as this second part is not related to #1465
