### ISSUE TITLE
Auto Shot and Stopcast

### ISSUE THREAD

**Issue by ghost** [SunstriderEmu/BugTracker#1469]
**Bug description**
/stopcasting stops auto shot
e.g. the following macro requires 2x /stopcasting (1st to stop auto, 2nd steady):
```
/startattack
/cast Steady Shot
```

**Expected behavior**
/stopattack for auto
/stopcasting for steady

**Comment by Jerrythemagicdog** [comment]
Auto Shot is a cast in itself, the macro Hunters use is:
```
/cast !Auto Shot
/cast Steady Shot   
```
is there any proof that /stopattack should stop Auto Shot?

**Comment by earthworm-jim** [comment]
afaik the only difference between !Auto Shot and startattack is, if you have 'Auto Attack/Auto Shot' toggled off in Interface->Combat settings, !Auto Shot will not try to melee the enemy, if you're in melee range.

> is there any proof or good reason that /stopattack should stop Auto Shot?

auto-attack and auto-shot are mutually exclusive (although on a different timer). sometimes you want to stop a casted ability (like Steady in my example) without interrupting auto-shot. further, multi-shot is also a cast, yet you can't stop it via /stopcasting (believe it only works for abilities that show the castbar, could be wrong). 

> @Bluespirit
I just tested this.
/stopattack DOES in fact shut off auto shot.

[classic wow discussion](https://us.forums.blizzard.com/en/wow/t/hunter-auto-shot-macro-help-wow-classic/187106/5)

there is some indication that this changed with 3.0, due to Auto Shot changes in wrath: https://wowwhimsy.wordpress.com/2008/08/27/13-hunter-macros/

**Comment by Jerrythemagicdog** [comment]
Auto Shot has a hidden cast time that requires you to stand still for some short period of time. 
Multi-Shot is an instant ability.

Classic is an entirely different game with a different client, perhaps it's handled differently there.
I'd like to know what are the implications of not being able to stop your Auto Shot with /stopattack before we look into this.

**Comment by earthworm-jim** [comment]
> Multi-Shot has always had a short cast time (even when it used to be labeled as an instant attack), and thus cannot be used while moving.

(even stated in the tooltip)
Currently both /stopattack and /stopcasting interrupt autoshot.
The problem is that /stopcasting must be pressed twice in order to interrupt any ability that shows the castbar (e.g. Steady, Aimed, Grenade...). If not, the ability will go off and then autoshot will continue anyway.

**Comment by kelno** [comment]
Seems invalid to me, if I'm auto attacking both command make the client send exactly the same query to the server asking to stop the current auto repeat spell (`CMSG_CANCEL_AUTO_REPEAT_SPELL`).

"The problem is that /stopcasting must be pressed twice in order to interrupt any ability that shows the castbar (e.g. Steady, Aimed, Grenade...). If not, the ability will go off and then autoshot will continue anyway."
> I can't reproduce that one, only one press of /stopcasting interrupts both for me

**Comment by earthworm-jim** [comment]
try
```
/cast !Auto Shot (or /startattack)
/cast Steady Shot
```
on the initial cast, the castbar disappears on the 2nd /stopcasting. subsequent casts, the 1st /stopcasting hides the castbar, but steady still goes off.

also swapping targets seems to reset autoshot cast. pretty sure that's wrong, but i will look for proof.

**Comment by kelno** [comment]
For last one https://github.com/SunstriderEmu/BugTracker/issues/629

**Comment by test-1337** [comment]
currently it's required to press /stopcasting three times (as a hunter) in order to interrupt steady/aimed etc. (instead of one press)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed since then.
