### ISSUE TITLE
Range on some abilities and spells is maybe too big.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#1485]
**Describe the bug**
**This report is researched and made by Oldsalt.**

> Ok so basically the main issue I see and which requires a fix before checking anything leeway related is that different spells use different distance measuring values which is obviously wrong as you can see with the warrior paint example.
> 
> Basically we have 2D, 3D and 3D point-to-point. This last one is the correct distance between two targets and doesn't use objectsize (combatreach, hitbox). All spells should use 3D point to point (+ combatreach on PvE).
> But currently on Endless :
> 
> Spells using 2D/3D (all the spells listed here have +2.5 more range than they should) : 
> Ranged auto attacks (only for the maximum value)
> Ranged abilities (instant, casting and channeled spells which require a target)
> 
> Spells using 3D p2p : 
> Ranged auto attacks (only for the minimum value)
> Melee auto attacks
> Melee abilities (damaging and non-damaging ones)
> AoE abilities (damaging and non-damaging ones)
> Cone abilities
> Destination spells

Screenshot to better portray the issue:
https://media.discordapp.net/attachments/625757439660392452/630525662041735168/unknown.png

Some examples include:
Warrior's Charge: https://cdn.discordapp.com/attachments/525320741420531742/630527847064141854/unknown.png
The "deadzone" for the Charge (min 8 yards) is bigger than expected.

At the same time range of spells such as Frostbolt is bigger than expected.

**Comment by kelno** [comment]
The "no combat reach in PvP" thing is false, I'm sure of it. It's been proven again and again by TC.
Another thing that can be used to validate this is, with the charge for example:
When the client shows a spell in red it doesn't even TRY to send a cast to the server, it just fails locally. If you're at 11 yards it will do so. Even if we wanted to change that we couldn't without using a client patch.
The max range at server also currently match the UI on this.

Melee also currently uses the combat reaches, the formula there is well known as well with:
`attacker combat reach + victim combat reach + 4/3` which is usually about 5 yards in PvP.

A lot of points are mentioned here though and it could be that some are incorrect, but I'd rather work with specific example than having to double check again all those myself and prove they are correct or not.

**Comment by Oldsalt0** [comment]
The melee formula is supposed to be the maximum between what you state and 5, that's pretty much why it is 5 yards.

Based on the following blue post : https://us.forums.blizzard.com/en/wow/t/hunter-beta-issues-update/223166
> Hunter “dead zone” is working as expected and is consistent with the Reference Client

(and the hunter "dead zone" on classic is 5-11)
I know their "dead zone" has been removed in 2.3, I'm just using it as a reference since hunters and warriors shared a same "dead zone".

This would mean it is accurate that ranged auto attacks take combat reach into account (no point to point calculation), so 11-38 yards instead of 8-35 and the same goes for hunter ranged abilities.
We could extend that to their categories : ranged auto attacks/ranged abilities, and this would also back up the 5-11 charge dead zone for warriors being a ranged ability.

-> Potentially an evidence it is blizzlike that some abilities use different distance measuring methods even if technically speaking it doesn't make much sense.
