### ISSUE TITLE
[Warlock] Demonic Knowledge does not update after aura application/level up

### ISSUE THREAD

**Issue by hufsa** [SunstriderEmu/BugTracker#1522]
**Describe the bug**
Demonic Knowledge Rank 3 should increase the Master's spell damage by an amount equal to 12% of the active demon's Stamina plus Intellect. And it does, when you summon your pet.
However, if the pet later gets a buff that increases stamina or intellect, the spell damage bonus is not updated. 

Also does not update when you level up and your pet gets more stamina/intellect.

NOTE: Master Demonologist which is supposed to increase resistances by 1 per level when having a fel hunter pet is not updated on level up either.

**To Reproduce**
1. Create warlock, .level 65
2. Pick Demonic Knowledge talent
3. Summon Felhunter
4. Take note of your spell damage
5. Cast a buff on your pet that gives stamina or intellect
6. Observe that the spell damage is not increased

**Expected behavior**
When your pet gets more stamina/intellect the spell damage from Demonic Knowledge needs to be "refreshed".

**Comment by Jerrythemagicdog** [comment]
Possibly related "Hey you got some issues with %flat dmg increase modifiers when you reapply debuffs. Atm as long as you dont let the debuff fall completely off it wont taky any changes in consideration. Tbh idk how to call it https://youtu.be/gJrTQCHsCJk"

**Comment by TheMoneyHater** [comment]
It should be added after all the modifiers though?

**Comment by Anderstegnel** [comment]
Yeah this is quite a big "deal" for PVP and for the PVE playing DEMO's. seeing its been up since december makes me quite sad. 

Its more like there is some kind of "cap" or something as it does not go above 95 when it really should.

Now even if I (player) get buffs, that increase the demons stats it does not either increase the value, Please fix guys its important!

Its quite a lot missing spellpower when ur all fully raidbuffed..

**Comment by hufsa** [comment]
Fixed with next update.
