### ISSUE TITLE
windfury totem attack power bonus

### ISSUE THREAD

**Issue by dogster39** [SunstriderEmu/BugTracker#1558]
When Windfury Totem procs from a yellow attack the Attack Power bonus of the spell gets added to the Attack power tooltip of the player until the next white melee attack lands.
This can be a problem in a few different ways:
1. The Attack Power bonus of Windfury is consumed on the next white melee attack and that melee attack is an Offhand attack making the bonus attack power be "wasted"
2. The Attack power bonus of Windfury affects both the Extra Attack proc and the next white attack making Windfury better than it should be

1.  Create a Warrior
2.  Hit a target with Heroic Strike/Cleave while affected by Windfury Totem 
3.  Pay attention to the attack power of the character going up when Windfury procs

**Expected behavior**
Windfury procs, player's attack power tooltip remains unchanged(this needs research), Extra Attack procced from Windfury receives the Attack Power bonus, other attacks are not affected.

Video of attack power change: https://streamable.com/t73xh

Additionally it appears Windfury procs are trackable using Procodyle addon, not sure if this is correct or not but here is how it looks: https://imgur.com/ohVPESu - notice how sometimes the Windfury Attack buff lasts for 1 or 2 seconds and during this time the character's overall attack power is increased.

shoutout to Rattacrash

**Comment by zanthed1** [comment]
This seems fairly consistent with how WF totem works on Classic. There is a nice wiki writeup by warrior theorycrafters here https://github.com/magey/classic-warrior/wiki/Windfury-Totem
There weren't any changes to WF totem from classic to TBC to my knowledge, if there were feel free to correct me and post updated sources.

**Comment by kelno** [comment]
Should be fixed with 13008
The "heroic strike" didn't remove a charge on the windfurry buff as it should have.

**Comment by kelno** [comment]
Waiting for blaze to give some details here he seemed to think it was different for TBC.

**Comment by kelno** [comment]
Okay apparently that classic research is valid for us.
The way the buff should work is as following: The buff has two charges, meant to be consumed instantly by the two melee hits.
But heroic strike doesn't consume the charge as it should because it's not considered as an auto attack hit.

So what we changed here is to make heroic strike and other "on next melee hit" spells proc as auto attacks as well.
But for now we decide to keep it this way, since it's clearly the intent and we feel it looks like a bug if we don't. 
(This change will be listed with upcoming list of custom changes)

**Comment by kelno** [comment]
Reversed that last change to go back to blizzlike state
