### ISSUE TITLE
[Item] Vial of the Sunwell

### ISSUE THREAD

**Issue by Aeded** [SunstriderEmu/BugTracker#1601]
**Describe the bug**
Does not come fully stacked upon entering to arena.

**To Reproduce**
1. Enter arena while having Vial of the Sunwell equiped
2. You have no stacks and have to cast spam heal during preparation time to fill the trinket

**Expected behavior**
Vial should be fully stacked upon entering arena.

**Additional context**
Its just a minor issure, they had this on Warmane and it was nice not having to worry about it. Never searched if it was blizzlike behaviour or not.

**Comment by Rettiy** [comment]
Autostack probably not blizzlike judging by some comments:
https://www.wowhead.com/item=34471/vial-of-the-sunwell&bonus=4080#comments
_"3. After you get buffs out in arena, spam Rank 1 heals to get a head start on the stacking effect for an early use"_ and similar...

What I'm emphasizing is **do not make it autostack for every class**, because I can see it potentially favoring some double dps comps. For example RM should have no way of stacking it, even though I can personally see some potential running it such as Bauble in wotlk.

List of classes that should be able to stack it:
- **Priest, Druid, Shaman, Paladin** -- obvious
- **Hunter** through Mend Pet (confirmed on the same page above)
- **Warlock** through Health Funnel (dtto)

**That leaves us with Mage, Rogue and Warrior not being allowed to enter arena with this trinket stacked.**

Quick fix/adjustment would be appreciated since it's gonna be used on PTR only for a while.

**Comment by Jerrythemagicdog** [comment]
Thanks!
Live with next restart.
