### ISSUE TITLE
Gruul's Lair - Gruul (various issues)

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#1628]
- [x] The stoned debuff (33652) before damage is too short
- [x] Gruul attacks in melee during the shatter
- [x] Pets shouldn't do stone damage (but should be stoned)
- [ ] The slow before the stone should be removable by shapeshift? Need proof here. Also if changes, have to change the spell script logic because it relies on the slow debuff being there.

**Comment by Drayo** [comment]
"The slow before the stone should be removable by shapeshift? Need proof here. Also if changes, have to change the spell script logic because it relies on the slow debuff being there."

No need to change, it is correct as it is. Slow must not be removable by anything.



Small additions that still need some testing:
- I was a bit late yesterday so I could not test it properly, but shatter damage must not be reduced by armor.

- Is Shatter supposed to be pre-nerf? If so it should do damage from ~20y instead of ~15y.

- Blessing of Protection must not grant immunity to being turned to stone. (Should be impossible in all cases actually)

- Cave in damage must not be tied to LoS

- Frequency and timing of abilities has to be checked, esp. the timing of the silence since him using it often after the shatter would make the boss nearly impossible early on.

https://wowwiki.fandom.com/wiki/Gruul_the_Dragonkiller?oldid=642044 
"Cave In: Random AoE which causes ~3000 damage every 3 seconds in the area. This occurs more frequently in later stages."
- Implies Cave in should work similar to the Vashj bats and should increase in frequency over time.

- Can you cast ANYTHING while silenced? Need to test BoP.

- Can multiple "Cave In" be up at the same time? Should be able to.

- Does Growth increase his melee attack range?

- Is Hurtful Strike only used on melee? Does he use Hurtful Strike on melees even if they stand at absolute max melee range? Even after multiple multiple stacks of growth?

**Comment by kelno** [comment]
Fixed all this.
Except for Shatter ignoring armor for which we didn't find any evidence. A good way to prove it would be finding a video clip where someone gives and receive the same amount of damage from shatter to a close player.

**Comment by Drayo** [comment]
> Except for Shatter ignoring armor for which we didn't find any evidence.

https://www.youtube.com/watch?v=06rYTdIwX8I&feature=youtu.be&t=3m2s

Watch the Combat Log at 3.07.

Awake and Tharghan hit **each other** for 2072 dmg, even though they are a Paladin and Priest respectively.

**Comment by kelno** [comment]
Nice that's good proof, I will update with that rule.

**Comment by kelno** [comment]
The slow is not removable again, will have to find another method.
Spell here: 33572 
We can fix it by just adding MECHANIC_SNARE to it.

**Comment by Jerrythemagicdog** [comment]
Updated with MECHANIC_SNARE here, works now.
