### ISSUE TITLE
[Druid] Lifebloom final tick

### ISSUE THREAD

**Issue by Aeded** [SunstriderEmu/BugTracker#1651]
**Describe the bug**
Lifeblooms final tick benefits from current bonus healing, instead of bonus healing that was present upon cast. Same issue occurs with Gladiator Idol of Tenacity.

**To Reproduce**
1. Use healing staff and any Gladiator Idol of Tenacity, cast lifebloom
2. Unequip staff and idol before lifebloom is finished
3. Lifebloom last tick heals for the amout of current bonus healing.

**Expected behavior**
Final lifebloom tick healing should be calculated from healing bonus present on cast.

**If needed here is some proof:**

https://youtu.be/yyaK3qTbsVI?t=6m20s
Druid has casted lifebloom on himself when wearing Y bonus healing+548 heal from mace
(You can see the icons next to player frame portrait to indicate which weapons he has equipped)

Final tick heals him for 1218 into catform (+20% heal) while he has equipped dps staff instead of heal mace. So base value before 20% heal from talent was something like 1015.

https://youtu.be/yyaK3qTbsVI?t=2m27s
Druid has casted lifebloom on himself when wearing X bonus healing+548 heal from mace
(You can see the icons next to player frame portrait to indicate which weapons he has equipped)

Final tick heals him for 1043 while he has still equipped heal mace.

The reason why both values (1043 and 1015) are not same is because he had more agility equipped in one of those cases. Lifeboom HoT ticks were 141 for 1043 final bloom and 135 for 1015 final bloom.

**Comment by kelno** [comment]
See https://github.com/SunstriderEmu/BugTracker/issues/157 
Now that I look back at it I think the conclusion there is wrong but there is definitely something going on since the used HB on the final tick in source 1 is definitely lower than the one used for ticks. While it should be higher because of "Nurturing instinct" talent

**Comment by Aeded** [comment]
Well if he was using Idol of the Emerald Queen then there is your mistery

**Comment by kelno** [comment]
Okay good idea, I'll redo calculation using that

**Comment by kelno** [comment]
Thinking about this again, the idol doesn't change the conclusion here.
I didn't account for Gift of Nature at first, so redoing the calc:

While in human form, ticks at 135:
135  * 7 = (HB * 0.52 + 273)*1.1
-> Deduced HB = 1127

He then does a final tick at 1218 on himself in cat form:
(600 + HB2 * 0.343) * 1.2 * 1.1= 1218
-> Deduced HB2 = 940

To validate those formula I also did the same test with a character in game to see if I obtained the same HB two time without changing gear, which I did.
So it appears again that the HB hasn't been snapshoted since the Healing Bonus used changed.

But I think this is just an oversight on Blizzard part and it makes complete sense to me that it should. And I don't see any downsides.
Thus I've updated and it will now shapshot, cheers!

**Comment by Aeded** [comment]
Well actualy... it is a feral druid, he does have Mangle talent, which means he does not have Gift of Nature at all. 
That means: 
135 * 7 = (HB1+Idol of the Emerald Queen * 0.52 + 273)
-> Deduced HB1 = 1204

(600 + HB2 * 0.343) * 1.2 = 1218
-> Deduced HB2 = 1205

**Comment by kelno** [comment]
I stand corrected, thank you
