### ISSUE TITLE
[Priest] Vampiric embrace

### ISSUE THREAD

**Issue by ramadansteve** [SunstriderEmu/BugTracker#1666]
VE heal should be capable of critting, currently isn't

**Comment by Aeded** [comment]
no

**Comment by earthworm-jim** [comment]
Patch 2.0.10 (2007-03-06): The base healing percent from "Vampiric Embrace" has been reduced to 15% from 20%. In addition, this ability can no longer get critical heals.

ofcourse there's a chance that was reverted

**Comment by Aeded** [comment]
I dont understand why such reports are marked as "research needed" instead of deleted instantly. If OP atleast tried to invest time into checking facts, beyond creating useless report with one sentence in it, he would find out that VE heal is not supposed to crit.

**Comment by ramadansteve** [comment]
i dont have the time right now to check facts etc. i noticed it when playing classic and assumed it was blizzlike behaviour so i reported it when i had a moment so that i wouldn't forget it

**Comment by Jerrythemagicdog** [comment]
Thanks for the sources here!

**Comment by SUN-Leekie** [comment]
@Aeded I understand where you are coming from but please note that everyone is trying to help to make the server as good as possible.
I added the label simply because the issue didnt have any source to back it up and I didnt have the time to find one eventhough I knew it was wrong.
Thanks to @earthworm-jim, we know have a solid source and if this issue arise again (probable with classic going on), it will be close instantly.
