### ISSUE TITLE
[hunter] trap trigger radius too low

### ISSUE THREAD

**Issue by ghost** [SunstriderEmu/BugTracker#1699]
https://streamable.com/u2dx8
https://i.postimg.cc/R0NGj7GT/trap-radius.jpg

**Comment by Jerrythemagicdog** [comment]
What's the video trying to show? Every race has the same hitbox size on the server. Was the druid mounted before taking this clip? That would explain the big circle.

**Comment by earthworm-jim** [comment]
tauren was just a coincidence

https://youtu.be/VhCI3DDvGGU?t=12m29s
https://youtu.be/zdrAtIkxN_I?t=6m22s
https://youtu.be/zdrAtIkxN_I?t=9m37s
https://youtu.be/yzGjRqu7YxQ?t=6m45s
https://youtu.be/yzGjRqu7YxQ?t=5m33s
https://youtu.be/Q6SP7TqdaOQ?t=43s
https://youtu.be/kqc7G3f0kro?t=1m3s
https://youtu.be/MXXDKcHm5Bo?t=29m19s
https://youtu.be/MXXDKcHm5Bo?t=2m13s
https://youtu.be/MXXDKcHm5Bo?t=4m50s
https://youtu.be/MXXDKcHm5Bo?t=6m23s
https://youtu.be/MXXDKcHm5Bo?t=6m54s

(distance seems to be greater in some of these due to batching/lag)

**Comment by earthworm-jim** [comment]
https://youtu.be/9hExikWBzpI?t=2m3s
