### ISSUE TITLE
[Rogue] Shadowstep - damage buff affects Shiv

### ISSUE THREAD

**Issue by sposobniy** [SunstriderEmu/BugTracker#1732]
Describe the bug : title 

Shadowstep - incorrectly 

To Reproduce : 
Use shadowstep - cast shiv , Shiv consumes Shadowstep buff

https://wowwiki.fandom.com/wiki/Shadowstep?oldid=1523989 
"If you are chasing an enemy you can Shadow Step then Shiv Crippling Poison them so they can't escape. Shiv does NOT consume the Shadow Step damage buff. " 
1) https://youtu.be/Ba6Ty72eSH8?t=230 Look at buff and how he press Shiv on 1 

2) https://youtu.be/Ba6Ty72eSH8?t=59 

3) https://youtu.be/Ba6Ty72eSH8?t=213 

I have some source  (uncorfermed ) shiv also should not affected "Dirty Deeds" - if anyone have some info ,and can help with this  will be soo good . Shiv some specific ability , Arena Junkies | Forum was closed i think i saw the information there .

**Comment by blblblaz** [comment]
https://www.youtube.com/watch?v=VdMIA6QkgFk&feature=youtu.be&t=395 - in this clip as far as I can see he doesn't press a single ability other than Rupture after using Shadowstep and as you can see it takes quite a bit of time for the Shadowstep buff to fade probably because of ping/spell batching/whatever

https://www.youtube.com/watch?v=VdMIA6QkgFk&feature=youtu.be&t=925 - in this clip he also didn't cast a ability outside of Rupture, and again you can see how delayed the fading of the buff is

https://www.youtube.com/watch?v=8KBoaYrNt9c&feature=youtu.be&t=298 - if you slow this clip down you can clearly see Shadowstep damage buff gets consumed after Garrote is casted but before the Hemo lands, and as you can see the application of Garrote itself is extremely delayed

But in these clips we can clearly see that Shiv doesn't consume Shadowstep, so we will look into that.
Not sure about Dirty Deeds and Shiv right now.

**Comment by Jerrythemagicdog** [comment]
Fixed with next update.
