### ISSUE TITLE
Paladin Trainers don't teach Parry

### ISSUE THREAD

**Issue by totaemoeggerli** [SunstriderEmu/BugTracker#1743]
**Describe the bug**
Some paladin trainer don't teach Parry:
[Tullas](https://www.wowhead.com/npc=17483/tullas)
[Kavaan](https://www.wowhead.com/npc=17121/kavaan)
[Jol](https://www.wowhead.com/npc=17509/jol)
[Vindicator Aesom](https://www.wowhead.com/npc=17844/vindicator-aesom)

[Baatun](https://www.wowhead.com/npc=16761/baatun) seems to be the only Draenei Paladin that can teach Parry. The dwarf paladin trainer at Kharanos was able to teach it. I didn't try any other NPC/classes.

**To Reproduce**
1. create level 8 paladin
2. learn Parry from the paladin trainer

**Expected behavior**
Every Paladin trainer should be able to teach Parry at level 8.

**Screenshots/videos**
https://imgur.com/a/VoeQy9U

**Comment by Jerrythemagicdog** [comment]
Thanks!

**Comment by Sheikthecatman** [comment]
Thanks, and fixed!
If you do find more paladin trainers missing Parry or other spells, do inform me through a comment and I will re-open this issue.

**Comment by NeonicSupersonic** [comment]
Blood Elf paladin trainers still missing it. I havent tested 1st trainer in 2nd hub due to nature of my leveling route(https://tbcdb.com/?npc=16275), but one (or probably all) silvermoon trainers missing it. You might want to check org/uc ones aswell.

There also missing redemption quest for paladins in silvermoon(or it is wrongly chained).
1st quest of the chain is https://tbcdb.com/?quest=9677
however you should be able to get 2nd part (https://tbcdb.com/?quest=9678) from silvermoon trainer regardless of having/completing 1st one

**Comment by bokunogoku** [comment]
Draenei Paladin Trainer Jol is missing the quest for Redemption rank 1, https://tbcdb.com/?quest=9598

**Comment by kelno** [comment]
@Sheikthecatman Fixed?
