### ISSUE TITLE
[priest][spell] mind control

### ISSUE THREAD

**Issue by ghost** [SunstriderEmu/BugTracker#1758]
lacks the chance to break due to distance/resistance. iirc, it should reach 100% to break at around 20-25y distance (from the priest)

**Comment by Aeded** [comment]
Agaist mobs yes, agaist players no.

**Comment by test-1337** [comment]
https://youtu.be/VoDy2MAjrGk?t=5m7s

**Comment by Aeded** [comment]
Yea, well there is a good reason that there are bugreport guidelines. If you make one sentence report then dont expect anything good from it.
MC agaist mobs has a periodic chance to break based on duration and distance. But this is not the case for player targets. Agaist players the distance limit is set and there is no periodic chance to break MC.

> lacks the chance to break due to distance/resistance. iirc, it should reach 100% to break at around 20-25y distance (from the priest)

you used word "chance" which would mean that there is some sort of periodic tic that could break the MC even after 1s duration, if the priest was unlucky. Which is not true, not agaist players.

So why would you expect me to do work on your report. Maybe nextime use the report guidelines and you save time for the devs and others reading the report.

**Comment by test-1337** [comment]
> MC agaist mobs has a periodic chance to break based on duration and distance. But this is not the case for player targets. Agaist players the distance limit is set and there is no periodic chance to break MC.

any evidence to confirm that claim? (i'm not saying you're wrong.. usually such periodic checks are excluded in pvp)

**Comment by Aeded** [comment]
Not like its hard to find...

https://youtu.be/VoDy2MAjrGk
https://youtu.be/M6gGOaPUciw

If it had a periodic chace to break, it would have to be based on some input (distance, duration) which would mean that if you MCd player on max cast range of the spell (20 yd) it would have a very high chance of breaking in the first seconds. Which is just not true.

In neither of those videos will you find MC breaking prematurely. There are some short MCs but that is due to DR.

**Comment by Jerrythemagicdog** [comment]
Thanks, definitely missing the range restriction at the moment.

**Comment by Jerrythemagicdog** [comment]
Fixed since then.
