### ISSUE TITLE
[Druid] Drums are cancelling druid forms

### ISSUE THREAD

**Issue by Varanak** [SunstriderEmu/BugTracker#1776]
Drums of Battle/Speed/Restoration are currently taking druids out of their forms when drums should be able to be used while shapeshifted.

**Comment by networm555** [comment]
you shouldn't be able to drum in for at all

**Comment by kelno** [comment]
https://wowwiki.fandom.com/wiki/Drums_of_Battle
"Druids can use this drum in any form."

**Comment by kelno** [comment]
Fixed with 13255, the following items can now be used in druid forms:

24494, Tears of the Goddess
29528, Drums of War
29529, Drums of Battle
29530, Drums of Speed
29531, Drums of Restoration
29532, Drums of Panic
31088, Tainted Core
32406, Skyguard Blasting Charges
32456, Skyguard Bombs
32680, Booterang
32825, Soul Cannon
37815, Emerald Essence
37859, Amber Essence
37860, Ruby Essence
39969, Fire Seed
39970, Fire Leaf
40077, Crazy Alchemist's Potion
40771, Cobalt Frag Bomb
41119, Saronite Bomb
41265, Eyesore Blaster
41340, Fresh Ice Rhino Meat
42442, Tablets of Pronouncement
43059, Drakuru's Last Wish
44222, Dart Gun
49278, Goblin Rocket Pack
49633, Drums of Forgotten Kings
49634, Drums of the Wild
