### ISSUE TITLE
[Shaman] Tremor totems affected dispel  resistance tailents 

### ISSUE THREAD

**Issue by sposobniy** [SunstriderEmu/BugTracker#1793]
Describe the bug:
[Tremor Totem]'s dispel mechanic that is able to fail removing fear/sleep/charm effects. Probably the main cause is aura that provides chance reduction for caster's spells to be dispelled. For example some talents got this aura effect:
https://tbcdb.com/?spell=14787 seems like Priest's fear can be affected by this talent
https://tbcdb.com/?spell=30064 same for Warlock

To Reproduce:  
RNG factor , but sometimes not remove fear with classes with resistance tailents. 

https://youtu.be/15zMCG_Z-7E  Test in duel 

https://imgur.com/kuHzzhp  fails remove fear from teammate 
https://www.twitch.tv/sposobniy/clip/GlutenFreeIncredulousRatItsBoshyTime 

Expected behavior:  
Tremor totem can not  fails cos its not dispel

**Comment by Rettiy** [comment]
Same experience here, it's working incorrectly right now, Tremor totem is not a dispel but a remove, and therefore should have 100% effectiveness.

**Comment by hufsa** [comment]
Would need some proof here. Why would the effect behave differently only for this? Tremor totem effect (spellID 8146) uses the same effect as other spells, SPELL_EFFECT_DISPEL_MECHANIC. One for each type -- charm, flee and sleep

**Comment by Rettiy** [comment]
I would need a reason why rogues have 500% damage and are favored in literally every way on this server including custom changes fit for them xddddd.

This is beyond ridiculous you have 3 to 4 decent shaman players in TBC yet you still try to trash the class even more by questioning this and wasting time on such obvious things like this one. Purging the remaining 4 players who still try to play this useless class in PVP away. Absolutely brilliant.

1. It's nowhere listed in the whole history of Dispel page on wowwiki, probably isn't dispel then?
https://wowwiki.fandom.com/wiki/Dispel?action=history

2. Result of some searching, page is not available anymore although the wording there is quite obvious: https://imgur.com/a/TK0xn5M

3. https://github.com/Atlantiss/NetherwingBugtracker/issues/6426 gets fixed here without any doubts because people probably know by now how TBC works?
- in the same link above there's discussion about Death Coil _"it has the 'Apply Aura Mod: Fear' flag as far as spell mechanics go"_ so by your approach it's probably fair to start discussing whether Death Coil should be removable by tremor as well?

**Comment by Aeded** [comment]
Like Retti said, tremor is not dispel. Anyone who played WoW for more than week knows it... trying to make conclusions from client data is beyond retarded - sure it does work lot of times, but there are examples where it just doesnt work.

**Comment by hufsa** [comment]
I don't really see how I'm trying to trash the class by asking for this, haha.
I asked for this from a programming perspective as I'm trying to find a generic solution as to why the effect here should behave differently and how to implement it properly. 

As for the death coli/fear example that would have been a thing unless it also had EffectMechanic = MECHANIC_HORROR. 

Thanks for the provided links.

**Comment by hufsa** [comment]
Making conclusions from client data is the only way to properly implement the spell system. Thanks for your input though!

**Comment by hufsa** [comment]
Fixed. Live after next restart.
