### ISSUE TITLE
Quest Item Drops Feature

### ISSUE THREAD

**Issue by Ironjudgment** [SunstriderEmu/BugTracker#1812]
Hi, first I would like to thank the endless team for opportunities to test the server and provide feedback.
So, now’s the time for the meaty bit.

I would like to propose to you a small change to the current faction balance. It would be tremendously beneficial that both factions have a feature of grouped shared quest item drops. 

I strongly feel that there are many people who have played TBC for the nth time and would love this feature in the Horde side simply because levelling with friends is much more enjoyable with shared quest items drops and encourages people to play together.

I understand that it’s a feature that is supposed to draw players to the Alliance but after looking at the already proposed changes I feel that the Alliance already has a huge boost (650g free for riding, increased quest items drops, two PvP items for the price of one, rep boost).

Therefore, I am strongly advocating of implementing this feature server wide so everyone can benefit from playing with friends on equal terms instead of punishing half the server.

I welcome comments on this from the rest of the community :)

**Comment by Jerrythemagicdog** [comment]
Thanks for your feedback
There is no intended punishment here, shared quest drops are a feature, just on the Alliance side and not Horde. 
The point of these perks is that one side gets them and the other doesn't, otherwise they wouldn't be perks and faction incentives, however small they may appear. 
Every player is free to choose Alliance when they're creating their characters and we're leaving that choice to players and their friends with all the information about incentives available.
