### ISSUE TITLE
[Druid] & Fel Mana Potion not working

### ISSUE THREAD

**Issue by filipele0** [SunstriderEmu/BugTracker#1816]
**Describe the bug**
Fel Mana Potion doesn't regen mana over time while i'm in cat and bear forms

https://tbc-twinhead.twinstar.cz/?item=31677

**Expected behavior**
Please fix mana gain from Fel Mana Potion while being in cat/bear forms

**Screenshots/videos**
![Capture](https://user-images.githubusercontent.com/60582948/73616790-1d1fbc80-4618-11ea-93b2-f8fee0f91503.PNG)

Best wishes

**Comment by NeonicSupersonic** [comment]
It might be proper interaction. I mean, druid cant be mana drained in cat/bear, right? Why opposite should work then?

**Comment by filipele0** [comment]
i know only how it worked on hellground for years and on excalibur server and on few more, 
it didn't work on warmane tho, 
and i have no idea how to get info about core mechanics so i hope comparsion to other private servers will be enough

so i can only prove it worked on hellground by sending video of feral dps namaste using it in fights

here is a link https://www.youtube.com/watch?v=X0LDB6ckr-E
he used it in 0:55

**Comment by Aeded** [comment]
VT, JoW, Mana Spring Totem and Fel Mana potion (energize effects) are not supposed to work in Cat/Bear.

**Comment by Aeded** [comment]
@filipele0 Trying to prove something to be true just because it worked on previous trash servers? XD

https://youtu.be/5lXyQhuK9HA?t=343
JoW and neither Mana Spring Totem (energize effect) do not work while druid is in Cat Form -> All energize effect dont work in Cat/Bear -> Fel Mana Potion is (periodic) energize effect so it shouldnt work either -> bye

**Comment by Jerrythemagicdog** [comment]
Thanks for the research!
