### ISSUE TITLE
[Warlock] Drain Soul visual bug

### ISSUE THREAD

**Issue by Jerrythemagicdog** [SunstriderEmu/BugTracker#184]
**Description:**
When using Drain Soul (27217 for example), the Warlock gets the debuff icon on himsself even though he does not take damage himself. He should instead get a buff indicating that he's using Drain Soul (can't find a source right now. )
Screenshot of what's happening: https://imgur.com/a/MvxVm3f

**Expected behaviour:**

Should not get a debuff but a buff with Drain Soul icon. 
(like here https://youtu.be/XLmMHQErD88?t=531)

Otherwise, the spell works correctly.

**rev. hash/commit:** 

Sunstrider rev. 10283 (2e80439) 2019-01-22 18:43:47 +0100 (master branch) (Unix, DEBUG, Static)

**Comment by kelno** [comment]
Channeling can be a bit special because it's the same spell id for the buff on caster and debuff on target, and the core doesn't handle that correctly, it just has a positive/negative flag it will reuse for both. Need core support for that. I'd say that's low priority.
Could you try to list some other spells with the same issue? Probably all kind of drains.

**Comment by kelno** [comment]
Maybe fixed with b532dbd3b92f743acfbe017b3fa0dc7d40219d4d

**Comment by kelno** [comment]
Fixed!
