### ISSUE TITLE
[Warlock] Ritual of Summoning with random summons.

### ISSUE THREAD

**Issue by AshamedPlayer** [SunstriderEmu/BugTracker#1849]
**Describe the bug**
Warlock's target when casting Ritual of Summoning is being randomly changed (even few times during cast) without warlocks assistance. Server does the swapping while Warlocks keeps the same target whole time and then ports the "serverpicked" target.

**Screenshots/videos**
https://clips.twitch.tv/PrettiestSarcasticRadishDogFace

**Additional context**
This issue kept happening after relog of warlock more than 3 other times.

**Comment by Jerrythemagicdog** [comment]
Thanks!

**Comment by SabreValkyrn** [comment]
This also impacts summoning stones, making both methods of summoning your party highly unreliable.

**Comment by BoogieWoogie0** [comment]
Still actual. Fix this bug please.

**Comment by carverwarcraft** [comment]
Please fix this!! Incredibly annoying.

**Comment by carverwarcraft** [comment]
Please fix this!!! Should be a priority.

**Comment by AC619** [comment]
Please fix this!!! Should be an absolute priority.

**Comment by Photosynthh** [comment]
Have no Elvui or Xpearl and summons still do not work.

**Comment by tom291990** [comment]
Hi this needs fixing asap this is one of the most annoying bugs on this server.

Thanks

**Comment by Jalapan** [comment]
@Jerrythemagicdog please fix this, still an issue and its causing so much problems.

**Comment by SabreValkyrn** [comment]
Being ganked and killed at the stone because it takes 13 summon attempts to get one person isn't a particularly good user experience.

**Comment by bugreporterx** [comment]
@Jerrythemagicdog It's been almost two months since this issue was reported and this issue still persists on the server. Can you guys please give priority to this bug? The only workaround that is reliable as of now is that those using either a summoning stone or portal need to log back to the character screen, disable the addons, log back off and enable them. You can imagine how frustrating it must be for the playerbase. Thanks.

**Comment by Denagul** [comment]
I did some testing on what addons cause summoning issues and have found 5 Troublesome addons: Gearscorelite, Procodile, NarkarDrums, Omen2 and Diamond Threat Meter...there may be more, however these 5 are the ones in my library that personally caused me issues

If my warlock with no troublesome addons enabled targets my warrior who has troublesome addons enabled then my warrior is now targetting my warlock as if my warrior "pulled aggro" on my warlock since i turned and targeted him much like how creatures and bosses often turn and target spells at random players such as Dalliah the Doomsayer's Shadow Wave.

Much like how in PVP if an alliance player is not targetting anything and you start casting into them, they will target you just because you started a cast toward them before it even lands. This PVP scenario should be the ONLY exception to someone targetting someone randomly without the player manually targetting something from their client.

Again...these addons did not prevent me from summoning properly on previous private servers so I'm confused why Endless is having such a problem with summons.

**Comment by Sheikthecatman** [comment]
Most likely fixed in [3f53477c8e68954fcddd14f64eb5908ecdc60855](https://github.com/kelno/sunstrider/commit/3f53477c8e68954fcddd14f64eb5908ecdc60855) which should be live.
