### ISSUE TITLE
[Quest] Rescue the Survivors!

### ISSUE THREAD

**Issue by ammenvale** [SunstriderEmu/BugTracker#1878]
**Describe the bug**
"Saved" Draenei Survivors do not despawn

**To Reproduce**
1. Find a Draenei Survivor NPC that is in a untapped (lying on the ground)
2. Cast Gift of the Naaru on NPC
3. Gets credit for quest, NPC runs a bit then stops and doesn't despawn
4. The undespawned NPC does not give credit for quest

https://www.wowhead.com/quest=9283/rescue-the-survivors

**Expected behavior**
Draenei Survivor should despawn once saved and respawn in a untapped state for another player to complete the quest

**Screenshots/videos**
![WoWScrnShot_021820_195556](https://user-images.githubusercontent.com/45928535/74791565-c73e4c00-5288-11ea-97a0-a4f5750f9e01.jpg)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed after next restart.

**Comment by Djenery** [comment]
New bug with the quest. If you swapped your racial ability you can't complete the quest due to it required draenei ability to heal mob with it. Solution is to add the ability for who swapped their ability but with some conditions that prevent abuse it. For example if player leave the start location the ability should disappear and if back to start location it will appear again but only for draenei who also has another racial and has this quest in their quest log.
