### ISSUE TITLE
unable to accept ress as a ghost

### ISSUE THREAD

**Issue by michaelkittrell** [SunstriderEmu/BugTracker#2076]
this has happend a few times, but had it happen 3-4 times today.  could not click accept after walking to corpse as a ghost.  logged off logged back in same problem.  exit'd game (alt-f4), logged in still a ghost, still could not click accept. finally talked to spirit healer.

**Comment by michaelkittrell** [comment]
this specifically was happening in cenario refuge.  after being pvp'd by guards or alliance players.

**Comment by VSteeph** [comment]
**Describe the bug**
Your corpse is not spawning, so you can't accept the resurrection despite being at your corpse. It takes some time before the corpse to show up.

**To Reproduce**
It's kind of tough to give you a description because it happened to me only twice. A hint would be that it happens near cliff or bump in the ground, and maybe the corpse is falling.
