### ISSUE TITLE
Divine Shield and Divine Protection share CD

### ISSUE THREAD

**Issue by DollpartsFTP** [SunstriderEmu/BugTracker#2117]
Divine Shield and Divine Protection are currently sharing a cooldown

**To Reproduce**
1. Use one
2. Watch the other also get a 5 minute cooldown

**Expected behavior**

Cooldowns are individual to the spells (It even says in the spell tooltip that you will be unable to use the other for 1 minute)

**Additional context**
Imagine scripting core class mechanics instead of just giving alliance perks.

**Comment by AWIDIUS** [comment]
This is blizzlike behavior

**Comment by Godmatik** [comment]
> Additional context
Imagine scripting core class mechanics instead of just giving alliance perks.

Imagine coming here in acting like you know everything only to be proven wrong and then throw in a random insult at the end. Also, the perks were basically demanded by the playerbase during PTR/Beta because there was belief that anything less would lead to horde domination.

**Comment by DollpartsFTP** [comment]
So, 1 bug reported is wrong out of the 2000 bugs reported, and all of a sudden you think your server is well scripted and are going to fire shots instead of actually fixing class mechanics?

My statement stands. Should've fixed class mechanics rather than implementing alliance perks.
