### ISSUE TITLE
Hunter/Rogue breaking chain pull

### ISSUE THREAD

**Issue by Kratuzov** [SunstriderEmu/BugTracker#2234]
**Describe the bug**
When hunter pulls a pack, someone else hit the mob then hunter feign death or rogue dissapear, the mob keep attacking the person that attacked it and the rest of the pack keep running back. By doing this its very easy to pull always just 1 mob from supposed to be difficult packs. This bug works everywhere, in the world, in HC dungeons and even in Karazhan!

**To Reproduce**
1. Hunter pull
2. Tank shoot the target
3. Hunter feign death
4. Rest of the party can freely kill the target

Every single mob in the game

**Expected behavior**
Whole pack should keep attacking the group.

**Screenshots/videos**
I will provide video in case my explanation is not enough, didnt make one yet.

**Comment by Jerrythemagicdog** [comment]
Thanks!

**Comment by Ironjudgment** [comment]
Well, it might be a bug but it still is Blizzlike behaviour? Split pulling as a hunter has been in the game since vanilla and was actually essentiall to some dungeon/raid tactics. Although I agree this should not work on bosses, normal mobs should not be exempt. I couldn't find any tbc time split pulling vidoes but there are plenty in vannila ones like: https://www.youtube.com/watch?v=CBOwIyG98SY or https://www.youtube.com/watch?v=-wo7WYtTtL4

And from the hunter patch notes from vanilla till tbc there is no mention of 'fixing' or changing this mechanic. https://www.wowhead.com/forums&topic=181967#1-12-1

**Comment by Jerrythemagicdog** [comment]
Fixed a long time ago, thanks.
