### ISSUE TITLE
Character movement

### ISSUE THREAD

**Issue by mpenaz** [SunstriderEmu/BugTracker#2265]
Character movement feels really clunky and you can get stuck even from walking over a little bump or roughness, which you would just walk over without any issue on the retail server.

This is not as critical in the open world or pve content generally, but in the arena gameplay this is game changing critical issue.

To Reproduce: 
Ruins of lordaeron arena - try running around the middle tomb, or around where there are few pieces of wood lying around and you will see that you can definetly get stuck on those, which is not really a pleasant experience

**Comment by Jerrythemagicdog** [comment]
That's not something we control, the old client we're using has those issues, mostly commonly around the "ring" area in Blade's Edge Arena or on the tomb area in Ruins of Lordaeron. 
There are third party workarounds that some players use but we do not recommend using any third party software as your account may be locked due to an unrecognized client.
