### ISSUE TITLE
Pet spells is not in spell book even though it is trained

### ISSUE THREAD

**Issue by raol19ac** [SunstriderEmu/BugTracker#2333]
**Describe the bug**
I can only see 1 spell in my pets spell book. I have learned several pet spells.

**To Reproduce**
Open the pet spell book I guess

I dont know

**Expected behavior**
I expected to be able to use my pet spells

**Screenshots/videos**

Dont know how. But its an almost empty spell book with only first spell in it

**Additional context**

I tried taming a new pet. Had same problem

**Comment by mayday2013** [comment]
IF you are a hunter, then you shouldn't see any of learned spells from pet trainer.

You learn the possibility of teaching your pet this ability.

You should have Pet Training spell. Teaching pet for new abilities costs Training Points that can be found in your pet tab in C menu.

If you have tamed a new pet and it already has some skills, your pet's yp amount will be below 0. You have to level it's loyalty first to get these points back, and only then you can reset skills of your pet at pet trainer for 10s and learn the skills you need.

EG: If you are lvl 70 and you tame lvl 69 scorpid, it will have ~400 tp. At level 3 loyalty you will have 6 t, and lvl 4 - 79 and so on. That happens because this scorpid has Fire resistance perk and Scorpid poison r4 perk from the start. 

Takes a while to level it's loyalty.

As for me, I had been running with King B from lvl 43.

**Comment by raol19ac** [comment]
But there is no tab. That is the problem.
I've been playing hunter since tbc was live, so it's not because I dont know how to do things.
But thx for trying to help me out :)
