### ISSUE TITLE
SHH HC - stacked adds at second boss

### ISSUE THREAD

**Issue by B0nisek** [SunstriderEmu/BugTracker#2433]
add are stacking at second boss

![image](https://user-images.githubusercontent.com/22475895/77164558-d9422300-6ab0-11ea-960b-190791b3554c.png)

**Comment by mayday2013** [comment]
Can confirm. Archers are doubled if you wipe.

**Comment by h0rz** [comment]
Can also confirm, Zealot mobs double and stack instead of engaging regularly related to their staic timer and continue to be linked to Porugg, also the rogue which usually is within the first 3-pack on gauntlet "clones himself" occassionally after a wipe. Porugg may despawn randomly when you try to reset via FD / Vanish, rendering him unkillable in that ID. Wonder why this has not been officially tagged yet, Gauntlet part seems completely broken.
