### ISSUE TITLE
Kylene doesn't teach Cooking

### ISSUE THREAD

**Issue by beraus** [SunstriderEmu/BugTracker#2438]
**Describe the bug**

Kylene doesn't teach cooking.

Kylene: https://www.wowhead.com/npc=19186/kylene

**Screenshots/videos**

http://prntscr.com/rjvdpu

**Comment by Sheikthecatman** [comment]
[Fisherman's Feast](https://www.wowhead.com/spell=42302/fishermans-feast)
[Hot Buttered Trout](https://www.wowhead.com/spell=42305/hot-buttered-trout)
[Stewed Trout](http://www.wowhead.com/?spell=42296)
Might be missing, unsure if the cooking spell should be on her or if it was added in later patches (After TBC).

The recipes listed were added in 2.1.

**Comment by beraus** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/2412

**Comment by bjh368** [comment]
What part of this needs research? Wowhead comments says it's all added in patch 2.1.2 through the trainer function rather than a vendor function. 

https://www.wowhead.com/npc=19186/kylene#comments

**Comment by beraus** [comment]
Looks like she should be able to train those recipes, not sell them:
https://www.wowhead.com/spell=42302/fishermans-feast#comments
https://www.wowhead.com/spell=42305/hot-buttered-trout#comments
https://www.wowhead.com/spell=42296/stewed-trout#comments

**Comment by bjh368** [comment]
So I've been digging through web.archive.org after info regarding Kylene and her mysterious cooking training. This is what I've found:

The recipes are added to Kylene in patch 2.1.2 according to the [official patch notes](https://web.archive.org/web/20180216044855/http://eu.battle.net/wow/en/game/patch-notes/2-1-2).
"Some new cooking recipes are available from Kylene in Shattrath City."
[Old wowhead comments](https://www.wowhead.com/npc=19186/kylene#comments) from 2.1.2 also indicates that it was made available then.
Thottbot has an [archive page](https://web.archive.org/web/20070707111816/http://thottbot.com/i33052) for fisherman's feast from july 7th 2007, which puts this in 2.1.2, with a comment saying: 
"You can find this recipe in Shattrath in the Lower City in the tavern. The barmaid trains you on all 3 new recipes that go from 3g to 5g a recipe."

But on the wowpedia page, it claims that "After Patch 2.3.0, she was also a special cooking trainer, the only one who offered the recipes below." However, there is no mention of her in the patch notes, nor in the undocumented changes. (checked live versions and archive versions.) Which does make this a bit suspicious, considering what we found in the patch notes from 2.1.2

So where does this come from? Well, on the archived pages from wowwiki.com/Kylene, t[he earliest page](https://web.archive.org/web/20071103052801/https://wowwiki.com/kylene) simply says: 

"With the new patch, she sells some cooking recipes:
Stewed Trout
Fisherman's Feast
and Hot Buttered Trout"

And this is from 3rd November 2007, which would put this during patch 2.2, the pages for the specific recipes have their earliest archive from October 12th. Do note that this doesn't mean that it was created during this time, only that the earliest archive is from this time. Regardless, it's before patch 2.3. Wiki pages from these times are very unreliable, never has sources, and are updated very rarely, especially for minor stuff like this, so the "new patch" could be 2.1.2, no way of knowing for sure. 

[The archived page from January 22, 2008](https://web.archive.org/web/20080122031122/http://www.wowwiki.com:80/Kylene) (after patch 2.3.3), says: "Since Patch 2.3.0, she is also a cooking trainer who teaches the following recipes:..." And this is the only source I found indicating that Kylene and her recipes had anything at all to do with patch 2.3. This info stays in all versions of the wowwiki page, and also carried over to the wowpedia page. My hypothesis so far is that someone found the article on wowwiki which said "with the new patch", assumed  that it was written recently, and made it more future proof by adding the most recent patch number.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next restart.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next restart.
