### ISSUE TITLE
Dampen magic bugged?

### ISSUE THREAD

**Issue by wombo2u** [SunstriderEmu/BugTracker#2612]
**Describe the bug**
Dampen magic not reducing spelldamage taken.
example: https://gyazo.com/c9bf9713d27427f51ec6811db7334815
Im not sure its intended behavior or not.
**To Reproduce**

1. apply dot
2. cast dampen
3. still take same damage

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by blblblaz** [comment]
Dampen Magic works, the problem is that when you already have a DoT applied to you, and you buff yourself with Dampen Magic, the DoT's damage will remain the same because that's how DoTs work. For example if a Warlock/Shadowpriest's spell damage trinket has 1 second left and they cast a DoT, that DoT will tick with the spell damage bonus from the trinket for the entire duration. Dampen Magic works on the same principle so that's why the damage in your screesnshot isn't reduced.

Damage taken and healing taken is the same effect as the spell damage/healing stat found on some gear. For example, a warlock casting a damage spell on a target buffed with Dampen Magic rank 6 will have the same effect as if he had 120 less +damage on his gear. - from WoW Wiki
