### ISSUE TITLE
Righteous Fury & Improved Righteous Fury talent

### ISSUE THREAD

**Issue by zenoma** [SunstriderEmu/BugTracker#2619]
**Describe the bug**
The description of the buff is not right when you have the Talent active and I think it is bugged cause I cant generate the correct amount of Thread.

**Expected behavior**
Create the correct amount of Aggro

**Screenshots/videos**
My Omen addon threat meter is not working, or not displaying the amount of thread so I can't see the threat generated. 

![unknown](https://user-images.githubusercontent.com/15262243/77854176-ee256180-71e8-11ea-9808-380efc3b639b.png)
![unknown (1)](https://user-images.githubusercontent.com/15262243/77854177-efef2500-71e8-11ea-8820-d3a87c8b41d0.png)
![unknown (2)](https://user-images.githubusercontent.com/15262243/77854180-f1205200-71e8-11ea-8710-d2c44896679f.png)

**Comment by Naebu** [comment]
thats normal i think.. i played pally tank to and at your active buff always showed 60% thats no bug. you have the 90% for sure.

**Comment by blblblaz** [comment]
Ok, just did a quick test. You can loot at Omen in the screenshots, 99 threat/Concecrate tick unbuffed, 158 threat with untalented Righteous Fury, 188 threat/tick with Improved Righteous Fury.
The tooltip on your buff bar is only visual, the effect from the talent works correctly. need more details because everything is fine on my end.


![WoWScrnShot_032920_204230](https://user-images.githubusercontent.com/53877162/77856180-0e135000-71fe-11ea-8b6b-0bb31cf1d049.jpg)

![WoWScrnShot_032920_204255](https://user-images.githubusercontent.com/53877162/77856184-19667b80-71fe-11ea-86c8-30a04fdf63e6.jpg)

![WoWScrnShot_032920_204315](https://user-images.githubusercontent.com/53877162/77856188-1ec3c600-71fe-11ea-8ce0-78f1fe392518.jpg)
