### ISSUE TITLE
cheat death is bugged

### ISSUE THREAD

**Issue by fistymcfisto** [SunstriderEmu/BugTracker#2622]
**Describe the bug**
<cheat death is not working correctly. it procs and it will bring me to 10% hp or do the damage reduction>

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**
<! if you read the tool tip is says"You have a 100% chance thats an attack which would otherwise kill you will instead reduce you to 10% of your maximum health. in addition, all damage taken will be reduced by up to 90% for 3sec (modified by resilience).this effect cannot occur more than once per minute ". the amount of times that the animation for cheat death has shown above my head and i just die with no damge reduction or 10% manic is just stupid. it procs and i get ht harder than before or the damage reduction is random with no difference in resilience it can be a 10-50% damage reduction. i got killed there by a another rogue and the damage reduction with a melee hit got reduced from 133 to 103 damage. some times when im below 10% hp  cheat death will proc and my hp will jump bac k up to 10% and other tims it does not>

**Screenshots/videos**
<
>

**Additional context**
<>

**Comment by blblblaz** [comment]
In Patch 2.4.3, Cheat Death received a large change to it's mechanics. "Killing blows are no longer 100% absorbed. If the Rogue is below 10% health, the killing blow is still completely absorbed; if the Rogue is over 10% health, enough damage will be absorbed to reduce the Rogue’s health down to 10%. For the following 3 seconds, damage is not always reduced by 90%; it is now reduced by a maximum of 90%, depending on how much resilience the Rogue has. The damage reduction will be four times the damage reduction resilience causes against critical strikes.

from https://wowwiki.fandom.com/wiki/Cheat_Death_(rogue_talent)?oldid=1521553

would need video footage to really determine if something is wrong or not, because from your description it looks like it's working correctly
