### ISSUE TITLE
Hunter pet/Questing

### ISSUE THREAD

**Issue by bisquiit** [SunstriderEmu/BugTracker#2626]
Hey there
if a hunter gets a quest were he needs to kill an X amount of npcs for an quest.
he will not be resiving the kills if the pet is doing the killing Blow
so example i have to kill 10 npcs
if i land my shots for killing blow i will get 1/10 if the pet gets killing blow i will be 0/10

**Comment by blblblaz** [comment]
cannot reproduce, works fine for me, if it's possible for you to record a video of the issue happening it would be of great help!

**Comment by Skuzzlez** [comment]
I had this experience for a few quests while levelling, but the majority work fine. The one I remember off the top of my head where this issue was true, was the one where you have to kill the Ghosts in northern Dustwallow Marsh for information from the spirits that spawn on death: What's Haunting Witch Hill.

https://www.wowhead.com/quest=11180/whats-haunting-witch-hill

I'd imagine that because this isn't a 'kill credit' quest, but a separate trigger after a kill, it's granting that update to the pet and not the hunter. There were a few quests like this but this is the one that I remember.

**Comment by beraus** [comment]
If pet does a killing blow it doesn't credit the player, known issue, thanks.
