### ISSUE TITLE
[Hunter] Multi-Shot

### ISSUE THREAD

**Issue by bluemanguy112** [SunstriderEmu/BugTracker#2646]
**Describe the bug**
Secondary Multi-Shot Effect is affected by LoS. If Multi-Shot is used on a Target in LoS the secondary Multi-Shot effect should not be affected by LoS. Furthermore, the cone of the secondary effect seems to be way too small (needs further testing).

**To Reproduce**
Use a Pet Class and stand with Pet in LoS to the Hunter and the Player next to it out of Los -> use Multi-Shot on Pet.

**Expected behavior**
Multi-Shot to this day, on Retail WoW (BFA), ignores LoS on it's secondary effect.

**Screenshots/videos**
https://www.youtube.com/watch?v=dKx0KsCNBH4#t=452

**Additional context**
If this is somewhat the result of a custom change, it is inconsistent that Channeled Spells like Arcane-Missiles or Drain Life wouldn't be affected in the same way. Potentially Eleshaman's Chainlightning affected by the same Issue.

**Comment by blblblaz** [comment]
could be caused by the fix of https://github.com/SunstriderEmu/BugTracker/issues/1630

**Comment by Rettiy** [comment]
Since this server already implemented some custom stuff like no-hit through pillars in arena, it would be ridiculous to actually implement this on purpose.

Imagine chain lighting or multishot on totems to actually hit everyone else xddd

And since the idea behind no-hit through pillar was it is a nonsense, this is much bigger nonsense.

So please atleast be consistent in ur unjustified custom fixes.

**Comment by Skuzzlez** [comment]
The radius around the multi-shot is also definitely too small, as the OP hinted at. I can't find any evidence of what the radius should be, but even on Classic it's noticeably higher.

**Comment by ghost** [comment]
> The radius around the multi-shot is also definitely too small, as the OP hinted at. I can't find any evidence of what the radius should be, but even on Classic it's noticeably higher.

Thats because Combat Reach is not being added to the range against secondary/tertiary MS targets.
Chain Lightning and other abilities of that type likely have the same problem.

https://www.youtube.com/watch?v=iVbXDo3dfYA
https://youtu.be/mZXP5GwGuG4?feature=shared&t=281
https://www.youtube.com/watch?v=9qv4nbt-NNk&t=159s
https://www.youtube.com/watch?v=WnfPMwwvYtQ&t=12s

**Comment by kelno** [comment]
See https://github.com/SunstriderEmu/BugTracker/issues/5391#issuecomment-1768447350
