### ISSUE TITLE
No mining nodes inside dungeons

### ISSUE THREAD

**Issue by AgreeableNZ** [SunstriderEmu/BugTracker#2712]
**Describe the bug**

No mining nodes in any dungeons.
**To Reproduce**
Enter a dungeon with mining.

**Comment by elnium123** [comment]
Same problem here, no nodes in any dungeons, fix it pls.

**Comment by elnium123** [comment]
As always, no one will take the time to answer, sad .. and btw on retail TBC 12 years ago, node are inside steamvault lel

**Comment by iluminatix** [comment]
rip, that sucks, there are usually nodes in every dungeon, was on retail and every other project this far... chest-like, small bonuses to make those gather profs matter. furthermore to keep market in check - this is needed or prices will be way too high imo, since it makes up for some portion of the availble ores, gems, herbs :)

**Comment by beraus** [comment]
This issue should be fixed now.
