### ISSUE TITLE
Horde Faction balance is working

### ISSUE THREAD

**Issue by L1NSEED** [SunstriderEmu/BugTracker#2777]
**Describe the bug**
Horde faction bonuses need buffed.... Repuation. and 100% mount should be free. it is unfair that all alliance are able to 100% mount in PVP and gank via flying in WPVP because horde cant afford it ! 

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by lukas155** [comment]
Please don't clutter the bug tracker with irrelevant whining.

**Comment by AdriRepti** [comment]
So you tell me that 600 gold of grinding it's irrelevant whining no?
I mean it's like yea man get 600 free gold that other players grind in days of playing to buy items. I mean you deserve that just by joining the alliance. I understand if those things we're at least  payed with real money cuz this bonuses look like some microtransactions-tier bonuses to me 👍

**Comment by Goeb23** [comment]
> Please don't clutter the bug tracker with irrelevant whining.

Everyone on the server saw how your "faction balance" worked. Literally the alliance dominates the wpvp, there are always like 4+ alliance players on 1 horde and you can't even catch them because they fly away. I don't blame them, that's the true spirit of a pvp server.. I blame you for giving one faction HUGE bonuses over the other. And now when people start complaining about the problem.. you call it "irrelevant whining". I think some of you have some severe trauma bcs of the horde. I refuse to believe some server owners can be that blind. xDD

**Comment by Godmatik** [comment]
Faction balance was 65% Alli 35% Horde, it's now much closer, typically at around 55% Alli and 45% Horde after the faction changes. I see tons of Horde in open world and they constantly are now taking Terokkar Towers and Halaa and such.

If you take away the Alli bonuses completely, Horde will be dominate faction again just like in every other single TBC server.

**Comment by lukas155** [comment]
Faction balance is almost 50/50, yet still people will complain. It's incredible. No ones forcing you to go horde. You are choosing horde for the superior racials.

**Comment by Jerrythemagicdog** [comment]
Please keep this issue tracker for in-game issues only. Thanks.
