### ISSUE TITLE
Shaman Lighting bolt and Chain lighting

### ISSUE THREAD

**Issue by columbolajos** [SunstriderEmu/BugTracker#2838]
Shaman spell chain lighting and lighting bolt have the same damage. Chain lighting damage should be higher than the bolts damage.

**Comment by Jerrythemagicdog** [comment]
![image](https://user-images.githubusercontent.com/46463908/78959570-3dba3600-7ae3-11ea-882c-8bbec0776b5a.png)

**Comment by columbolajos** [comment]
Cast it a little bit more. Like 100 times each, then average.

**Comment by columbolajos** [comment]
> Cast it a little bit more. Like 100 times each, then average.

**Comment by Godmatik** [comment]
Keep in mind that Lightning Bolt has a higher spell co-efficient than Chain Lightning, meaning that it benefits more from +spell damage. 

This means that it is possible for Lighting bolt to eventually out-damage Chain Lightning once you have enough gear. Although Chain Lightning should still be incorporated into an Ele Shaman's rotation (if they have the mana for it) due to the faster cast time.
