### ISSUE TITLE
Druid in general

### ISSUE THREAD

**Issue by kybaliona** [SunstriderEmu/BugTracker#2993]
1. Druid dont have human detection when in cat form 
2. Your form cat/travel/bear breaks when you open something 
3. When you transform yourself in something else lets say you use  [Orb of Deception] to become grome and then you transform in cat or any other form you stay in gnome shape .. your spells are working fine but you look like grome with bear spells...

**Comment by oldspices** [comment]
leaving form when opening stuff is normal, 

as far as stealth detections I do feel the talents are scuffed because I have the same stealth level/detection as rogues (from ++ stealth items) yet they constantly find me first-I will have to test it with another account soon in diff specs / items for concrete evidence tho. 

 and the human form in OHF Is super annoying and ugly lol.

**Comment by kelno** [comment]
Thanks!
Druid have the same detection as others but their stealth is weaker than the ones of rogues with talents.
3d one is the only bug I see here, it's reported in another issue so I'll close this one.
