### ISSUE TITLE
Not a bug but I want to report a ninja

### ISSUE THREAD

**Issue by Jorgepvp** [SunstriderEmu/BugTracker#3014]
I'm Spanish player, excuse if my English isn't good u.u:

I was doing Arcatraz group with Nayko Warlock, when the boss went to die he changed to masterloot and did ninja on trinket and the healer piece, being warlock.
After I adviced the guild lead and he removed him from the guild but had bad attitude with me and the leader of his last guild.
I want to show screens. Take care with him and his alt.

And please, create a forum to this kind of issues... That kind of persons should be banned cause they are doing OUR server to be sad -_- It's not a thing to say "ignore him and gg" 

![Ninja changed masterloot](https://user-images.githubusercontent.com/63867799/79592250-05fe5000-80da-11ea-899d-5345ab09da35.jpg)

![Ninja items and leave](https://user-images.githubusercontent.com/63867799/79592289-131b3f00-80da-11ea-9f40-614949154558.jpg)

![alter nayko](https://user-images.githubusercontent.com/63867799/79592294-17475c80-80da-11ea-962b-4a65a1aa0883.jpg)

**Comment by Provil** [comment]
Due to your message on that support I ask him why did he done that, according to him the healer was afk almost the whole donjon and specially during boss, for you it seem that you died almost a thousand time in this donjon. All in all if you want to rage on someone on this support try first to learn the game and not to afk during donjon maybe after that you'll deserve to have stuff. (In case you don't know a healer trinker on an afk healer is useless :) )

**Comment by Jorgepvp** [comment]
> Due to your message on that support I ask him why did he done that, according to him the healer was afk almost the whole donjon and specially during boss, for you it seem that you died almost a thousand time in this donjon. All in all if you want to rage on someone on this support try first to learn the game and not to afk during donjon maybe after that you'll deserve to have stuff. (In case you don't know a healer trinker on an afk healer is useless :) )

@Provil 1 Being ninja WILL NEVER have a reason ^^ 2 I didn't died a lot as you say, 3 it's obvious that you are friend of that ninja and you are defending him... GG.

**Comment by Provil** [comment]
1 why would i defend him ? he has the loot now i don't care about defending him he's not going to be banned so even if i was his friend i have no reason to defend him on a forum that nobody is reading  (i think if i was his friend i would have insulted you but ok ) 2 if the masterloot excites it's for that kind of problems and that kind of occasion it's a function that excite in the game so that not illegal so i would say there is no reason not to ninja to someone who afk the whole dungeon

**Comment by kelno** [comment]
In any case for that kind of report in general you should use in game tickets, this bugtracker is about bugs only.
We don't handle ninja-loot cases currently.
