### ISSUE TITLE
Seal of the Crusader

### ISSUE THREAD

**Issue by LQuark** [SunstriderEmu/BugTracker#3030]
It seems that since the updates applied this morning when I judge the seal of the crusader the increase of the holy damage bonus does not apply at all.

**Comment by mchayes** [comment]
bump, this is retarded

**Comment by liepelt089** [comment]
bump, fix pls

**Comment by aadane** [comment]
yes, i have same problem! its harder to keep threat on bosses with this bugg

**Comment by davedave1991** [comment]
Not only that, Seal of righteousness went from tanks doing 400 to 140 dmg now

**Comment by kelno** [comment]
I'm guessing this is because of the Seal of Righteousness fix. It was taking FULL spell power coefficient from Seal of the Crusader, which was a bug.
See https://github.com/SunstriderEmu/BugTracker/issues/1644

If you got any evidence there is a new bug please post that on this linked issues with more details about how much it does/it should do.
