### ISSUE TITLE
Kindness quest dont work (bug)

### ISSUE THREAD

**Issue by Amatista14** [SunstriderEmu/BugTracker#3172]
https://www.wowhead.com/quest=10804/kindness

Does not work, follow the steps to complete the mission to the letter but the Mature Netherwing Drake do not go down.

Target : https://www.wowhead.com/npc=21648/mature-netherwing-drake
Need for quest : https://www.wowhead.com/item=31372/rocknail-flayer-carcass
Quest: https://www.wowhead.com/quest=10804/kindness
Spell: https://www.wowhead.com/item=31372/rocknail-flayer-carcass

![WoWScrnShot_042920_065646](https://user-images.githubusercontent.com/64528125/80583502-a9a70480-89e6-11ea-8d79-97d9bcc083fa.jpg)

**Comment by Rockbiter-shaman** [comment]
While this is a bug because the dragons are supposed to have a much farther range, sufficient to work on the ground which it currently doesn't, the quest is able to be completed by standing on a small hill in the middle of where the dragons are flying. I completed this quest today by doing this, but you must wait until a dragon is very close to the hill.

**Comment by kelno** [comment]
Thanks!
I have applied a fix which went live this morning
