### ISSUE TITLE
[Profession] [Blacksmithing] [Master Hammersmith]

### ISSUE THREAD

**Issue by MalenkiiMuqq** [SunstriderEmu/BugTracker#3207]
**Describe the bug**
My nick in game is Shmakaxik
<The problem is that having done the  [first part](https://ru.classic.wowhead.com/quest=5302/%D0%BF%D1%83%D1%82%D1%8C-%D0%BE%D1%80%D1%83%D0%B6%D0%B5%D0%B9%D0%BD%D0%B8%D0%BA%D0%B0) for the gunsmith, I did not take it into account. In the end, I can’t become a master of weapons. Who is studying at Winterspring with [Lilith->](https://ru.classic.wowhead.com/npc=11191/%D0%BB%D0%B8%D0%BB%D0%B8%D1%82-%D0%B3%D0%B8%D0%B1%D0%BA%D0%B0%D1%8F)
Also, I completely deleted the profession and studied it again, but this did not give any result, since this [NPC](https://ru.classic.wowhead.com/npc=11178/%D0%B1%D0%BE%D1%80%D0%B3%D0%BE%D1%88-%D1%81%D0%B3%D0%B8%D0%B1%D0%B0%D1%82%D0%B5%D0%BB%D1%8C) no longer has a task.
A huge request to help in this matter, since a huge amount of time and money has been spent and has provided a problem, because I can’t create the necessary things for myself by profession

**To Reproduce**
<To fix the down issue, I propose to issue this quest again, for re-execution, or to provide a ready-made master of weapons..>

![WoWScrnShot_043020_161310](https://user-images.githubusercontent.com/64593287/80846261-4e5a5980-8c14-11ea-8f74-6b983d576400.jpg)
![WoWScrnShot_043020_161615](https://user-images.githubusercontent.com/64593287/80846263-4f8b8680-8c14-11ea-93e9-562f8c1eddb6.jpg)
![WoWScrnShot_043020_161649](https://user-images.githubusercontent.com/64593287/80846265-50241d00-8c14-11ea-9050-29e630488de5.jpg)

**Comment by Eyon933** [comment]
you need to complete the weaponsmith quest before you can become a hammersmith

**Comment by MalenkiiMuqq** [comment]
> you need to complete the weaponsmith quest before you can become a hammersmith

I already completed the quest, but I indicated it in the report

**Comment by bugreporterx** [comment]
Did you go take the weaponsmith quest after you re-learned blacksmithing? If you forget the profession, you have to do the quest again.

**Comment by MalenkiiMuqq** [comment]
> Did you go take the weaponsmith quest after you re-learned blacksmithing? If you forget the profession, you have to do the quest again.

after I re-pumped the profession the quest never showed up

**Comment by Simon-GM** [comment]
You **DO NOT** have to reskill blacksmithing all together.

**First:** When you are a weaponsmith (after completing '**The Way of the Weaponsmith**'), you will be able to freely switch between the sub-specializations (axesmith, hammersmith & swordsmith) in Everlook at Kilram, Lilith and Seril. 
You simply have to unlearn your current sub-specialization _(can be done by interacting with the same NPC, that taught you the sub-specialization to begin with)_ before learning a new one. This act will cost you 100 gold. 

**Secondly:** After attempting to reproduce your exact situation, I have found that there might be an issue happening, when you reskill your blacksmithing all together. I have sent you a direct message in order to solve the issue with you.

Thank you for the report.
