### ISSUE TITLE
Error join to my account. 500  Error An error occurred while processing your request.  Request ID: 0HLVDI1NSJAKJ:00000001  Referrer: https://endless.gg/changes

### ISSUE THREAD

**Issue by Pedomaci47** [SunstriderEmu/BugTracker#3209]
**Describe the bug**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Pedomaci47** [comment]
Error 500, and when join to game, disconnect all of time

**Comment by patmanpost** [comment]
I get the same problem on the website. When I try to log in, it gives me this  Error 500. However I do not get logged out of the game. A friend of mine does get logged out of the game on a other server thow. this might also just be due to security programs or simular.

However.. This is what my  page looks like when I log in on the website:
![enless 500 login](https://user-images.githubusercontent.com/64697317/80868332-31686980-8c9a-11ea-9e37-1879125b134f.png)

**Comment by patmanpost** [comment]
I get the same problem whe nI log in on the website. It wont let me plogin.. It displays me the  error 500. I don't have problems ingame with disconnecting or simular, wich might be issued with sescurity programs on the users computer.

This is what the page looks liek when I try to login:

**Comment by patmanpost** [comment]
I get the same problem whe nI log in on the website. It wont let me plogin.. It displays me the error 500. I don't have problems ingame with disconnecting or simular, wich might be issued with sescurity programs on the users computer.

This is what the page looks liek when I try to login:

![endless 500 error login](https://user-images.githubusercontent.com/64697317/80868562-c750c400-8c9b-11ea-95dd-226d13939e21.png)

**Comment by beraus** [comment]
Contact us on Discord.
