### ISSUE TITLE
Successfully skinned a mob and not getting leather

### ISSUE THREAD

**Issue by Ezann3** [SunstriderEmu/BugTracker#3269]
**Describe the bug**
multiple times i have skinned a mob but did not get leather. the mob either just stays there unclick-able or just de-spawns. 

**To Reproduce**

1. kill mob
2. skin mob
3. if leather received, try again

raptors in Wetlands, 
Dragonkin in Dustwallow mash

**Expected behavior**
after skinning, i should receive leather

**Screenshots/videos**
![image](https://user-images.githubusercontent.com/64969328/81302568-20aa6000-90ad-11ea-9e4f-fea33294a56d.png)

**Comment by alanparrish** [comment]
any updates? quite gamebreaking bug i'd say

**Comment by miki-g** [comment]
i have 300/300 skin, so i dont know if i see this bug ( reported in 2020, now is 2022...) , or npc in dustwallow ( dragonkons - Firemane Xxx, clocolisks, ... ) disappear very fast before comlete skining,
not all, sometime skin ok, sometime body disappear without leather,

ps: due to posting to 2 years old bug, i have one question, server and developers are dead? server lifetime ending and only waiting to shutdown?

**Comment by Jerrythemagicdog** [comment]
Thanks for confirming this was still an issue. Fixed with next update.
