### ISSUE TITLE
Bag "Mission: Possible But Not Probable"

### ISSUE THREAD

**Issue by woonogit** [SunstriderEmu/BugTracker#3273]
I completed the chain of the class quest "Mission: Possible But Not Probable" (undead - rogue) and could not complete. When I wanted to pass the quest, in the inventory all the necessary items were mined but the button to finish the beat was not active. I canceled the quest in order to start the quest chain first but after canceling the class quest is not taken. Please, help. thank you.

**Comment by InhumanGM** [comment]
In order to replicate this issue, we need more information. Please follow the bug report template that way we can properly investigate this issue.

> **Describe the bug**


**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 


Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**


**Screenshots/videos**


**Additional context**

**Comment by InhumanGM** [comment]
This is due to an issue regarding bank storage that has been fixed already. Please create a ticket in-game for further assistance!
