### ISSUE TITLE
Increase trash respawn times (suggestion)

### ISSUE THREAD

**Issue by Majst** [SunstriderEmu/BugTracker#3313]
As we can see with T5 on this server, its very very hard and few guilds are able to be successful in clearing it. With this difficulty on a private server, it will definitely lead to people burning out and quitting, which I assume you guys are ok with as you want to have hard raids, which is totally cool.

I think since the content is so hard, making the trash respawn after 12 hours so you don't have to deal with it while progressing should be the first step you guys take before nerfing the bosses. The trash just kills motivation after it respawns on top of you while you are progressing and wiping to a boss. It is the worst part of progressing raids, and I think should be changed to not kill the server and have everyone quit because they don't want to deal with the time commitment.

**Comment by electro-shock** [comment]
It is meant to be like that, It is Burning Crusade. Was hard on original - played the whole content there and yes, it was hard. Our top guild was trying 2 months on Archimonde for example.. You want something easy? Play something else then, not Burning Crusade.
Don't feel insulted friend, I have no intention to do so.
But many ppl come to play BC because it is somewhat challanging.
Also, you need to clear lots of trash later, for example to craft shadow resistance gear for Mother Shahraz for the whole raid.

**Comment by Valdix** [comment]
12 hours respawn timer on trash is way too much, but I think increasing the trash respawn by another 30-60 mins would be actually good, this way guilds could have more attempts for the overbuffed bosses already (over 3x more hp).
