### ISSUE TITLE
BRD: Ribbly Screwspigot MIA

### ISSUE THREAD

**Issue by EL100** [SunstriderEmu/BugTracker#3326]
**Describe the bug**
For quest Ribbly Screwspigot, the NPC is missing in the bar. The quest is undoable. 3 of his cronies were and were hostile at the start. The cronies drop the lost thunderbrew recipe. Also these cronies respawn super fast,, like in 5 min or so.

https://classic.wowhead.com/quest=4136/ribbly-screwspigot#comments

**Expected behavior**
The NPC should be present and turn aggro (with his cronies) when you talk to him.

**Comment by Massie323** [comment]
If I remember from running BRD a few times on my rogue, it always looked like Ribbly died from some NPC. What I would see would be Hurley Blackbreath's Adds (but not himself), Ribbly's corpse if it hadn't despawned yet, and Ribbly's Cronies. 
Your argument of the Cronies respawning quickly would check out why I saw them being alive and Ribbly dead;
Because Ribbly AND the Cronies die from something when a fresh ID is created, and by the time you arrive at the Grim Guzzler, the Cronies will be respawned and Ribbly's corpse will be there, or be despawned if you took too long.
Another theory would be that Ribbly spawns neutral but his Cronies spawn hostile, and then there's an interaction of a neutral target aggroing hostile red targets and his cronies kill him. I don't remember if I saw a bugged faction flag on him like Booty Bay or something.

A GM could check this pretty easily if they teleport to Ribbly instantly after creating a BRD ID and seeing what aggros him.
Of course if they can access logs then that would be easier.

**Comment by Sheikthecatman** [comment]
Thanks! After the next server restart Ribbly will live a better and much longer life.

**Comment by EL100** [comment]
Thanks. Ribbly was alive and the quest is doable now. However his cronies were acting a bit weird. They turned aggro after I talked to Ribbly, but they didn't attack me nor could I attack them. So I stayed aggro'ed in the entire dungeon with them following me around. They don't aggro other monsters, but FD didn't get rid of the aggro either.
