### ISSUE TITLE
Battleground queues while in another battleground

### ISSUE THREAD

**Issue by Felynda** [SunstriderEmu/BugTracker#3337]
**Describe the bug**
This has probably been reported many times before but currently you can queue for 3 different battlegrounds at the same time (this is good.) Now let's say Warsong Gulch pops and we enter this battleground. The game starts normally and you are winning/losing, it doesn't matter. Now suddenly Arathi Basin pops and half your team dissapears instantly, maybe even the enemy team aswell. Causing an extremely unfun pvp experience. You almost never get proper games and many games end in timeouts when they were full 15v15 before. The most glaring example of bad gameplay is when one side is clearly winning. The losing side then has more insentive to leave, cause a massive disbalance in an already losing bg. 

**To Reproduce**
Just queue BG's for a day you will pull your hair out of frustration.

**Expected behavior**
To fix: When you join a battleground you leave all queues or put the other queues on halt.

**Comment by Luqmas** [comment]
I would just like to support this request. The described issue completely ruins the experience.

BGs starting 15v0 is no fun.
Having a full team of 15 people at the start only to have 13 leave before the gates are opened is no fun.
Having WSG end because there are not enough players right before you can cap your third flag is no fun.

Please make it so that when you are queued for 3 BGs and one pops and you enter it, the two other queues are postponed until you have left (either won or losed) the one accepted.

Thank you

**Comment by miakke** [comment]
I'd like to support this request. BG hopping is a huge issue. I just had EIGHT players simultaneously leave EotS game before the battle even commenced. Very frustrating.

**Comment by kellison007** [comment]
I 2nd this emotion.  When your char enters a bg, they need to commit or be a deserter.  If they have an option to just round robin and basically screw other people over by abandoning the bg without consequence then this isn't fair.  This current system is ruining BGs.  I honestly don't even want to log in and play bgs anymore since its always a 15 v 4 game.  Fix this please.

**Comment by kelno** [comment]
4ec42159139c446cbc5b32b5d6464519ab0c4813

**Comment by kelno** [comment]
Joining a bg now removes you from other bg queues after 1 min. (but it does not remove from arena queues)
