### ISSUE TITLE
Timber Worg Tails

### ISSUE THREAD

**Issue by quiksilver0** [SunstriderEmu/BugTracker#3368]
tails are not dropping for quest in terokkar forest. kill 10 + not 1 drop yet. 12 needed.

quest - https://www.wowhead.com/quest=10016/timber-worg-tails

**Comment by InhumanGM** [comment]
Upon attempting to reproduce the issue, I was not able to find any issues. Could you provide more information that could be used to try to reproduce the issue again?

**Comment by xxfortnitexd** [comment]
I also killed like  50 wolves till i got all 12. i dont think its bugged the drop chance is just extremly low.
My mate on the otherside killed like 15 and got all 12

**Comment by InhumanGM** [comment]
Are you attempting this quest as a Horde character? @xxfortnitexd

**Comment by quiksilver0** [comment]
> 
> 
> Upon attempting to reproduce the issue, I was not able to find any issues. Could you provide more information that could be used to try to reproduce the issue again?

Apolgoies im alliance human pally i got 1 after around 10 kills can confirm very low drop rate (including the alpha worgs) around stonebreaker hold

**Comment by xxfortnitexd** [comment]
@InhumanGM no iam alliance

**Comment by InhumanGM** [comment]
The item [[Timber Worg Tail]](https://tbc-twinhead.twinstar.cz/?item=25807) is dropped by three NPCs:

1. [Timber Worg](https://tbc-twinhead.twinstar.cz/?npc=18476) - 25% drop rate
2. [Ironjaw](https://tbc-twinhead.twinstar.cz/?npc=18670) - 25% drop rate
3. [Timber Worg Alpha](https://tbc-twinhead.twinstar.cz/?npc=18477) - 15% drop rate

Perhaps the drop rate could be increased if the issue is that bad. @Sheikthecatman

**Comment by InhumanGM** [comment]
The drop rate has been increased and will take effect after the next restart. 👍
