### ISSUE TITLE
bug of purge

### ISSUE THREAD

**Issue by Lolcrabbe** [SunstriderEmu/BugTracker#3449]
Hello !
After use my trinket [Essence of the Martyr] shaman purge buff of she !!

**Comment by Jerrythemagicdog** [comment]
Seems the trinket is dispellable and is actually a magic buff. 
At the same time it looks like a leftover because the trinket has some proc flags which were intended for something else and for it to have a magic effect proc (maybe similar to https://db.endless.gg/?item=28370). This doesn't make much sense comparing to other "on-use" trinkets like https://db.endless.gg/?item=29370 so we'll make it undispellable. 
Fixed with next update, thanks.
