### ISSUE TITLE
Fel Orc Scavengers QUEST

### ISSUE THREAD

**Issue by glickz** [SunstriderEmu/BugTracker#3478]
Mobs do not count when killed for the quest Fel Orc Scavengers
Quest: https://www.wowhead.com/quest=10482/fel-orc-scavengers

**Comment by Godmatik** [comment]
to  be more precise, if a pet gets the killing blow, it doesn't count. 

Only seems to affect this quest.

**Comment by Simon-GM** [comment]
Confirmed.

If anyone else gets the killing blow, than the player who tagged the specific mob in the first place, the player wont be rewarded for the kill. Including but not limited to hunter pets.

**Comment by smizzard** [comment]
This bug is for all quests that require killing enemies of a general type rather than a specific enemy (for example: [Put On Yer Kneepads...] in Shadowmoon Valley; [The Bloodmaul Ogres] in Blade' Edge Mtns). It seems if the hunter pet does more than 50% damage, the kill will not be recorded regardless of who gets the lasthit.

**Comment by hufsa** [comment]
Fixed some time ago.
