### ISSUE TITLE
Shadow Word: Death damage and/or scaling is too low

### ISSUE THREAD

**Issue by Kraizn** [SunstriderEmu/BugTracker#3749]
**Describe the bug**
The scaling for Shadow Word: Death is not correct. 

**To Reproduce**
1. Cast Shadow Word: Death(Rank 2) on enemy that has no modifier to spell damage taken.
2. Compare Damage to original values (e.g. video linked below)
3. Yikes

Spell: https://db.endless.gg/?spell=32996

**Expected behavior**
"Scaling : +100.00% of spell power to direct component"

**Screenshots/videos**

https://youtu.be/IXKy-lIwWQE?t=151
Shadow Word: Pain: 448 vs. Shadow Word: Death: 1366
Endless:
Shadow Word: Pain: 441 vs. Shadow Word: Death: ~ 1130

I tested this with 721 Spellpower, Shadowform, 5/5 Darknes, 5/5 Misery and 4 stacks of shadow weaving on a Rogue target with 337 resilience.

https://youtu.be/6JjgpeS0YDU?t=660
Here is shown Mindblast damage compared to Shadow Word: Death:
Mindblast: 1457 vs. Shadow Word: Death: 1359

Endless: (1053 Spellpower, NO Shadowform, 5/5 Darknes, 5/5 Misery and 4 Stacks Shadow Weaving on enemy)
Mindblast: 1476 vs. Shadow Word: Death: 1169

This should be accurate enough environment to show that something is wrong with the scaling. But it doesnt show exact values since resilience from enemy and Spellpower of Priest is unknown in the source i linked of course.

more Examples from the original game:

https://youtu.be/ukgAf3MVRM4?t=261
Mindblast: 1249 vs. Shadow Word: Death: 1117

https://youtu.be/ukgAf3MVRM4?t=345
Shadow Word: Pain: 495 vs. Shadow Word: Death: 1529 (LOL ?) 

**Additional context**

**Comment by Jerrythemagicdog** [comment]
The coefficient we're using is 42.86% - https://wowwiki.fandom.com/wiki/Spell_power_coefficient?oldid=951132

That just comes from a very generic formula used for a lot of instant spells. Perhaps there is another issue here with Shadow Word: Death not being affected by one of the talents, looking into that now.

**Comment by blblblaz** [comment]
> Endless: (1053 Spellpower, NO Shadowform, 5/5 Darknes, 5/5 Misery and 4 Stacks Shadow Weaving on enemy)

I did a quick test with 1053 spell damage - https://streamable.com/yxljyg
I believe you may have used Rank 1 Shadow Word: Death in your test on our server because as you can see Rank 2 SWD pretty much doesn't go below 1300 damage with 1053 spell dmg, at the end of the clip I start spamming Rank 1 SWD and the damage more or less matches the one you got in your test.

Keep in mind SWD has a damage range and partial resists are a thing but from watching this video that you linked https://youtu.be/ukgAf3MVRM4?t=345 - his SWD throughout the video does anywhere from 1150 to 1300 or so with different amounts of Shadow Vulnerability and in your example he has Icon used in order to do 1525 SWD so he probably has around 900 spell damage unbuffed and with that in mind those damage values kinda match ours at first glance

**Comment by Kraizn** [comment]
Yes thats true - wrong number in macro. Thx and sry for waisting your time.
