### ISSUE TITLE
Freezing Trap resisting a huge amount in PvP

### ISSUE THREAD

**Issue by Skuzzlez** [SunstriderEmu/BugTracker#3759]
**Describe the bug**
Freezing Trap (all ranks) is resisting far more than it should. This is most likelybecause the traps are incorrectly considered lower level than their targets on this server, giving them a much higher resistance chance than normal.  The highest level Freezing Trap can get is Level 60 at rank 3, which gives it an abhorrently high resist chance against level 70 targets. This massively affects hunters in PvP and is pretty gamebreaking to be completely honest.

**Intended Behaviour:**
https://wowwiki.fandom.com/wiki/Patch_1.7.0
> The resist rate for hunter traps is now based on the hunter's skill rather than the level of the trap.
Traps should resist at the same rate as normal spells at the hunter's level and not based on the level of the spell.

**Comment by Jerrythemagicdog** [comment]
Need some details and reproduce steps, when testing against a naked level 70 character with no talents that could interfere the spell isn't "resisting a huge amount". 
I made a mistake explaining it here: 
https://github.com/SunstriderEmu/BugTracker/issues/3402
the level of the caster is used when casting the trap.

**Comment by bluemanguy112** [comment]
Don't know if you build in exceptions for BG/Arena environments, but I also get about 70 % of my Traps resisted even with Trap Mastery specced. Don't know what you guys did, since it was completly fine at the end of s1. Especially Rogues (given Heightend Senses) seem to Resist pretty much close to 100% (at least I can't remember the last time I did not get my trap resisted by a Rogue in BG). Also worth mentioning that Trap Mastery should entirely negate all these Talents and therefore resisting should be impossible.

**Comment by Skuzzlez** [comment]
I'm getting about 30% of my freezing traps resisted in PvP as Marks. This is pretty triggering to be honest.

**Comment by dalepo** [comment]
I'm having the same issues with my pet nova (Frost mage). I can confirm on the last days around 20-30% of my Freezes are getting resisted with 60 spell penetration and 3% hit, which is kinda weird.

**Comment by artieau** [comment]
Working correctly.
