### ISSUE TITLE
Shaman DPS increase bug with rockbitter and Windfury.

### ISSUE THREAD

**Issue by Taunted** [SunstriderEmu/BugTracker#3760]
**Rockbitter and windfury Weapons stacking up**
<The bug is basicly applying two diferents weapon buffs to make them stack up>

**Just apply Rockbitter first to ur both or 2h weapon then unequip them Afterwards equip ur weapon back then change it to wf then unequip and equip again just to make sure it worked but in that time u prob already has an melee increase dps from rockbitter and wf.**
 
U can also (click off ur wf weapon buff while ur stats melee screen open and it will drop ur weapon dmg afterwards making this u confirm that bug exists. Also Works with double rockbitters stacking up withc

But honestly don't need too much just go bgs and 25man raids enhanc shammys doing* one shot to everybody (not like the usually one shot) and doing more dmg than hunters and warlocks.

Rockbitter Weapon: https://tbc-twinhead.twinstar.cz/?spell=10399
Windfury Weapon: https://tbc-twinhead.twinstar.cz/?spell=25505

![bug](https://user-images.githubusercontent.com/62585136/85227373-7617a380-b3b3-11ea-8b87-22fac711b444.png)
![normalrock](https://user-images.githubusercontent.com/62585136/85227376-79ab2a80-b3b3-11ea-836c-9eb665c69974.png)
![unbuff](https://user-images.githubusercontent.com/62585136/85227379-7c0d8480-b3b3-11ea-9e4a-c765de7d2a3c.png)

I am actually surprised that not an single shaman report that bug cuz it's affective changes ur gameplay in pve and pvp but i guess it's because they are abusing of that.

That's it.

**Comment by Taunted** [comment]
The pictures are from unbuffed,with rockbitter and with the bug. And it stacks with windfury aswell. But i don't have an shaman at wf weapon buff to give u guys screen shots.

**Comment by cssarto** [comment]
yes, this bug is being used a lot by many shaman players, Gm needs to adjust this soon.

And there is also a druid bug, which after performing the respective on the website, the 5% critical aura is still active.

**Comment by likekille** [comment]
Fix this!!

**Comment by cssarto** [comment]
![WhatsApp Image 2020-06-21 at 12 22 01](https://user-images.githubusercontent.com/17818760/85228537-47e99200-b3ba-11ea-857f-33d935477101.jpeg)
![WhatsApp Image 2020-06-21 at 12 22 01 (1)](https://user-images.githubusercontent.com/17818760/85228539-4c15af80-b3ba-11ea-905b-af985f04c231.jpeg)

this is bug Druid aura

**Comment by Taunted** [comment]
This druid bug and rockerbiter can be associated with server auras. Both dind't remove their earlier buffs while changing for an new one similar to previous one. Rockbitter/wf    bommy aura/Resto aura.

**Comment by cssarto** [comment]
Ajust this bug too please.

**Comment by TheMoneyHater** [comment]
I'm sorry to tell you all but this was a RETAIL BUG THAT LASTED THE WHOLE EXPANSION
https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-emulator-servers/wow-emu-exploits-bugs/109411-shaman-buff-stacking.html

This should not be fixed or be considered a bug.

**Comment by Taunted** [comment]
Endless ain't a 100% patched blizzlike server Alliance paladins have Seal of blood and horde paladins has seal of vengeance. Taunt resists is based on melee hit hating not on spell hit and so on. If it was considered by blizz an bug back then soo Endless can remove it earlier too. Bug it's a bug not matter when it was fixed in the expansion.

**Comment by TheMoneyHater** [comment]
Idk man, Im not seeing enh shamans above hunters and warlocks as u stated. And there is 0 above 1870 rating so idk man. There is only a few guilds that even uses enh shamans in 25 atm.

**Comment by michaelkittrell** [comment]
melee is weak throughout early tbc its not until bt where they're average and swp until they get the gear they need to dps and contribute like other classes.  leaving a bug in the game to make one specific type of melee more viable is ... a very questionable decision.  

If you wanted to boost windfury or melee swings/threat so melee is more viable without significantly increasing hunter/pet dps that would be an interesting decision that could help address many flaws in the original tuning and design of raids that cause melee to almost always be a sub optimal choice.

**Comment by kelno** [comment]
Thanks, fixed with next server update

**Comment by Doodlewang** [comment]
> Thanks! We discussed it and decided to fix it.
> Fixed with next server update.
I tried to message you Kelno but here is my only option I guess.  While I can't speak for enh shamans doing tier 6 content I can speak on behalf on the high level pvp enhancement shaman community when I say you changing this has effectively made enh shaman useless in areas. I really don't understand why you decided to fix this when it was a none issue to start with and had been around since TBC.

It's not like enhancement shamans were now suddenly overpowered and dominating the ladders when when infact even using this bug they were 2nd tier comps at best in 3v3 and basically shit tier in 2v2 with only 1 enh shaman being above 1850. 

With this bug they stood a chance at matching the DPS of a warrior/rogue and without this they will be doing approximately 50% less. No longer will a healer need to even worry about an enhancement shaman at all.

Watch very closely over the next week the results of this change because you will no longer see enhancement shaman among the 2k ratings anymore. Only Double healer warrior, WLD, RMP and Ret/War/healers.

**Comment by BasedForfrost** [comment]
I'd like to echo Doodle's sentiments from a PvE standpoint to say that I think its a wrong choice to fix a bug that existed in all of TBC's lifespan. With this, enhancement will now exist as a support through and through. They'll be stuck dropping whatever totems the group wants and dual Annihilators because their damage doesn't matter anymore. This bug is what made Enhance competitive with the other melee classes, and I'll concede that it might have buffed them a little too much in early tiers. But now they're falling behind warriors and rogues anyways. End game raiding guilds are probably only going to bring one enhancement shaman with the bug existing anyways. They're just losing damage for the sake of losing damage.

**Comment by cssarto** [comment]
bug is bug!

if the class is not happy, just create another

**Comment by TheMoneyHater** [comment]
50% less damage wtf are u talking about Doodlewang. Enh is still gonna be pog

**Comment by BasedForfrost** [comment]
50% less is an exaggeration for sure, but they are definitely losing a ton of damage. In Arenas, there's something like only five enhancement shamans in the top 50 teams in both 2v2 and 3v3 (actually I think all of them are in 3v3). This bug doesn't make enhancement shamans some unstoppable boogeyman it makes them competitive. Their representation is going to fall off a cliff. It's been awhile since I play enhancement without rockbiter + WF, but I assure you its something like a 20% damage loss. That's huge.

"Bug is bug" does not capture how big of a change this is to enhancement and I think the coming weeks will show that.

**Comment by Doodlewang** [comment]
T6 enh shamans already forced to use lvl 58 annihilator's or sit on the bench. Nice change devs.

**Comment by Rettiy** [comment]
People are actually trying to justify the most obvious Bug there has been on the bugtracker xd

**Comment by Doodlewang** [comment]
> People are actually trying to justify the most obvious Bug there has been on the bugtracker xd

Yeah man! I can't believe this was in the game for the whole of the TBC expansion and used through all of the content while being well known to Blizzard.  
Fuck letting a spec be competitive in 1 bracket of arenas. We only want to see RMP, WLD, Ret-Cleaves, Spell Cleaves and double healer warriors. No enh shamans allowed in 3v3... ESPECIALLY not in 2v2.   Also lets ignore that the server is overtuned and this allowed enh shamans to stay relevant as a DPS spec. Fuck that man!

**Comment by Doodlewang** [comment]
>Overtunes the content which requires extreme min maxing to be cleared
>Gimps a whole spec that wasnt even at the top of DPS Meters and had a B tier presence in areas whole still getting stomped by any competent team who knows how to CC

**Comment by ichibirofl** [comment]
> > People are actually trying to justify the most obvious Bug there has been on the bugtracker xd
> 
> Yeah man! I can't believe this was in the game for the whole of the TBC expansion and used through all of the content while being well known to Blizzard.
> Fuck letting a spec be competitive in 1 bracket of arenas. We only want to see RMP, WLD, Ret-Cleaves, Spell Cleaves and double healer warriors. No enh shamans allowed in 3v3... ESPECIALLY not in 2v2. Also lets ignore that the server is overtuned and this allowed enh shamans to stay relevant as a DPS spec. Fuck that man!

I'm with you my man, I just leveled and started gearing an enhancement like 2 weeks ago, had to start my own groups everytime cause I could barely trespass the "RDPS / WARLOCK MAGES ONLY" barrier just for being melee, and now I lost around 200 ~ 280 dps and can barely compete with mid geared warriors or rogues lol

**Comment by Shamiroquai** [comment]
The probelm now its eaven worst, I use to have between 900 to 1100 DPS melee damage, now im almost 50%!!! cant belive it, and this no solve my problem i need help now

**Comment by TheMoneyHater** [comment]
okay yeah with the WF change also its 50% 🤣 so boring

**Comment by kelno** [comment]
Well thanks for the input here, I'll make sure it's discussed again

**Comment by Doodlewang** [comment]
> Well thanks for the input here, I'll make sure it's discussed again
Thank you Kelno. I think we all appreciate you discussing it again and hope you can change it back to what it was.

**Comment by TheMoneyHater** [comment]
@Doodlewang Not the way it was, just the windfury. Because that will be enough. Having 2 nerfs on the same reset is whats making people so evolve in this. I main a hunter and in pve or pvp there is just no chance for a enh the way it is right now.

**Comment by Doodlewang** [comment]
> @Doodlewang Not the way it was, just the windfury. Because that will be enough. Having 2 nerfs on the same reset is whats making people so evolve in this. I main a hunter but I can see that in pve or pvp there is just no chance for a enh the way it is right now.

Not for pvp.  We arnt on our target constantly so the 3 second cooldown wont matter much. Most of the time we are stuck in roots/slows and rely on burst for our damage input.  We wait at least 3 seconds anyways.

**Comment by ichibirofl** [comment]
> Well thanks for the input here, we'll be discussing that a bit more

Thank you man. Take in consideration also that we deal with elitists on the server every freaking time so yeah, we enhancements might as well be tossed into the trash with our fully geared 700 dps

**Comment by TheMoneyHater** [comment]
@Doodlewang What do you mean? The rockbite stacking should stay removed, but the windfury 3cd sharing between the weapons, that's just to much.

**Comment by Laszlo548** [comment]
I never even knew about the rockbiter thing so I don't mind that no longer been here, but the difference with the windfury nerf is ridiculous, like all I was doing is been competitive with the dps by playing my class well. Now it's ridiculous, the nerf has just put a huge downer on all the time ive spent on this character. It should be put back to normal, there was no inbalance, the server has ran really well so why nerf a class that is already partly 'support' ?

**Comment by GenepoolWoW** [comment]
Hey Jerry, I've really noticed my annihilator uptime going down. Since you've nerfed WF can you at least slightly buff annihilator proc rate? Because that's really what I want to be doing. Thanks m8!

**Comment by BasedForfrost** [comment]
Windfury sharing a cooldown with both weapons is a bugged that Blizzard fixed in 2.1 according to the following post (linked by oj449 in the Windfury ICD thread): https://blue.mmo-champion.com/topic/18050-tbc-enhancement-shaman-faq/

From what we've seen in this thread, the Rockbiter bug existed the entire time. I can't find any information on whether or not Blizzard addressed the issue during TBC's life. 

With that said, it seems perfectly reasonable to keep the Windfury change but revert the Rockbiter stacking bug as that was part of the TBC experience (albeit I'm sure not many people knew about it). I just don't see the need in fixing both when the spec wasn't dominant in either PvE or PvP beforehand, especially when (as others have stated) these have both been known for awhile and left alone until now. I thank you guys for reconsidering the changes that were made.

**Comment by Laszlo548** [comment]
I disagree, at the end of the day, we are on a overtuned server, and it wasn't like raids were taking 5 enhance shamans was it? T6 is where rogues/warriors get their holy grail T6 whereas shaman's T6 (BT/MH) is shocking.  So it isn't really going to improve. It's a private server, it's not supposed to be like the game 100% or else we may as well have it identical, it had more balance in pvp/pve with this, isn't private server's about making the experience even better? It's just a drastic change no one was even asking about. Not everyone even knows about the Rockbiter thing, and still won't. :(

**Comment by Doodlewang** [comment]
> @Doodlewang What do you mean? The rockbite stacking should stay removed, but the windfury 3cd sharing between the weapons, that's just to much.

Ideally both removed back to the way it was before. But I personally would be fine if they reverted the rockbiter stacking change since this effects pvp more more severely then the windfury one.

**Comment by GenepoolWoW** [comment]
Disclaimer: this is a PvE opinion. I don't have the experience to comment on enha PvP.

Let's look at this issue from a different perspective. Did enhancement shamans ever need a buff? People are saying that nobody was asking for this change, that it's too much and that enhas are now sitting on the bench. But I feel we fail to actually look at how broken enha is to begin with. The utility we provide is almost unrivaled. Especially now with most raids boasting a roster of four or more hunters and actually bringing melees to raids. We could be at the bottom of the meters and we'd still have guaranteed raid spots. The high personal damage is just the cherry on top.

And let's also not kid ourselves on our personal dps either. Our damage is only going up from here. Enha, just like practically every physical dps class, scales incredibly well. I don't think the harsh reactions over these nerfs are quite justified. Of course, it's frustrating to lose personal dps but at the end of the day it won't affect enhancement shamans significantly enough to impact our viability for raids in my opinion. With proper itemisation and the mindset that we are a support class at heart we can continue to be a significant addition to every raid roster.

**Comment by Doodlewang** [comment]
Well to give you a good idea of how this will effect PvP I'll try to sum it up as simply as possible.

Before this update an enhancement shaman could be somewhat viable in 2v2 with a priest or healer. You will struggle hard to hit 1850 but it was at least possible with a bit of luck. Only 1 shaman did this and I got pretty close a few times but any half decent team will crush you since you are still playing a gimped team that doesn't have an advantage over any others. 3v3 is where a enhancement shaman suddenly became a viable spec to create teams around but was still a 2nd tier comp that was easily handled by any RMP and other comps if they knew to just CC the shaman.  

Now after this change you can quite literally replace the enhancement shaman with nearly any other class/spec and it will be better. Having an enhancement shaman within your 3v3 team is literally gimping yourself for no reason. 

The difference this has made for PvP is night and day.  Going from a semi viable 2v2 spec to literally not viable in 2v2 at all. Going from a viable of 3v3 combinations to gimping every team you are in.

**Comment by BasedForfrost** [comment]
@GenepoolWoW I agree with you that in the end enhancement shamans are very much a support class, just like elemental shamans, moonkins, ret paladins, or shadow priests. But there's two problems I have with the decision here. The first is why are we fixing things that (as far as I can tell) existed during retail TBC? The Windfury ICD? Fix it. It was fixed in 2.1 There's evidence of that. Rockbiter bug? Looks like it was always there. To those of you who think WF bug should exist instead of Rockbiter, I would ask you why aren't we buffing ele shamans? Moonkins? Ret paladins? Spriests? It's because this is recreating the TBC experience,  not class balancing for Wrath of the Lich King.

The second problem I have is what exactly did both of these fixes accomplish? @Doodlewang hit on the PvP to which I agree this is just going to result in enhancement falling into obscurity in arenas. As a PvE player myself, the result is a spec that will almost always be represented by 1 raid slot lost a ton of damage in an overbuffed raid environment. Nothing more, nothing less. These bugs existing didn't cause raids to stop bringing warriors and rogues and bring more enha shamans. It simply made enha more satisfying to play at a personal level. It feels better to be more competitive with the rest.

**Comment by Laszlo548** [comment]
@BasedForfrost I disagree, we aren't recreating the whole TBC experience, because this server is nothing of the sort, it is a overtuned server compared to TBC, where there is actually a opportunity to balance things a bit more. I can see your second paragraph levels things a bit more. The key is always trying to balance things out, then you have people playing those classes and overall a better experience. 

Think about it, before the nerf, were shamans destroying meters? No, nowhere near, but as your second paragraph states, they we're just making it in my opinion a lot more satisfying, especially in T6 as i state, the gear is nowhere to be seen for us. we gradually get a big better in our dps, whereas rogues have a big gear increase,warriors, etc..... the rockbiter thing, was obviously something that is a bug in my opinion, because you need to do certain stuff for it to work. The Windfury CD just made things a bit more interesting, and added a bit more dps

**Comment by TheMoneyHater** [comment]
Now, having to have Windfury/Flametongue for more overall damage is so meh gameplay wise.

**Comment by nagamash** [comment]
Is there any ETA on when you make a decision? I need to change how i spend my arena points if you stick with the nerfed wf and removed rockbiter and buy a 2h. :)

**Comment by Doodlewang** [comment]
So I have had a chance to play a good 50 games or so of 3v3 as enhancement and just as expected this change basically gimped enhancement into oblivion. 

Enhancement now has the honor of being spec with the least survivability in pvp but also has the honor of being the least threatening to any healer. The only semi viable comp left is Warrior,Druid, Enh and even that comp is better off with a ret paladin for cleave plus coming into s3/s4 there is a shitload of wizward cleave which are an instant lose anyways. Enhancement is literally the worst spec for any arena comp to include all because they can't do shit to survive and now can't do shit to kill anything.

"Hey guys, what if we just gimp one of the worst specs in pvp thats only semi viable as it is? Surely thats a bright idea that won't piss every single player of that spec off!"

I regret spending a single dollar on this server.  Brainlet retard devs. 


Literally gimping the

**Comment by Doodlewang** [comment]
So I have had a chance to play a good 50 games or so of 3v3 as enhancement these past few days and just as expected this change basically gimped enhancement into oblivion. 

Enhancement now has the honor of being spec with the least survivability in pvp but also has the honor of being the least threatening to any healer. The only semi viable comp left is Warrior,Druid, Enh and even that comp is better off with a ret paladin for cleave plus coming into s3/s4 there is a shitload of wizward cleave which are an instant lose anyways. Enhancement is literally the worst spec for any arena comp to include all because they can't do shit to survive and now can't do shit to kill anything.

Enhancement is 100% the worst spec in the game to bring into the 2v2 bracket. I would rather bring a prot spec then this into 2v2. 3v3 isnt far behind. 

"Hey guys, what if we just gimp one of the worst specs in pvp thats only semi viable as it is? Surely thats a bright idea that won't piss every single player of that spec off!"

I regret spending a single dollar on this server. Brainlet retard devs.

**Comment by ichibirofl** [comment]
Guess that's it then, no more feedbacks

**Comment by Laszlo548** [comment]
Bring back Rockbiter at least! Something which didn't even get changed on TBC..

**Comment by gnutkekw** [comment]
Bring back either rockbiter or windfury! enhance totally gutted

**Comment by Jerrythemagicdog** [comment]
The only source linked by @TheMoneyHater (https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-emulator-servers/wow-emu-exploits-bugs/109411-shaman-buff-stacking.html) is on a private server exploit forum posted under
`World of Warcraft Emulator Servers > WoW EMU Exploits & Bugs` which is very far from proving that this was indeed a thing on retail. Not a single retail source, class guide or a player from those times is able to point to this being a thing either. 
Whether this impacts class representation is another debate, although it seems dubious looking at points raised by @GenepoolWoW and raid setups in general.

**Comment by BasedForfrost** [comment]
Raid setups will always have one enhancement shaman, no more no less. All this did was cut their damage in half, sending them from middle of the pack to dogshit. They're buff bots. They were buff bots in retail, and they're buff bots now. Thanks for your time.

**Comment by BasedForfrost** [comment]
Pack it up boys if you felt good about being enhancement its time to feel content with being a buff bot or playing something else

**Comment by Doodlewang** [comment]
Hey guys check it out! 

Before
3-4 Enhancement shaman above 2k in 3v3
Now
0 Enhancement shaman above 2k in 3v3 

That sure was a great change you Devs made. Keep up the good work you retards.

**Comment by Doodlewang** [comment]
> The only source linked by @TheMoneyHater (https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-emulator-servers/wow-emu-exploits-bugs/109411-shaman-buff-stacking.html) is on a private server exploit forum posted under
> `World of Warcraft Emulator Servers > WoW EMU Exploits & Bugs` which is very far from proving that this was indeed a thing on retail. Not a single retail source, class guide or a player from those times is able to point to this being a thing either.
> Whether this impacts class representation is another debate, although it seems dubious looking at points raised by @GenepoolWoW and raid setups in general.

I personally played an enhancement shaman in TBC and it was a known method to use. The post was made in 2008 or some shit which was during TBC which is a source.

**Comment by gnutkekw** [comment]
Guess we have to wait for classic tbc KEKW
