### ISSUE TITLE
[Important] The base critchance of hunter pets is not working

### ISSUE THREAD

**Issue by TheMoneyHater** [SunstriderEmu/BugTracker#3843]
![image](https://user-images.githubusercontent.com/11985642/86172793-38d3b400-bb1f-11ea-96fc-90faae8ad686.png)
The base critchance on hunter pets are not working

**Comment by jebossue** [comment]
Can confirm that, with the test i made this afternoon : its the same thing with cat and with BM spec (10% crit), i just have 11% to 12% crit on pet everytime (same for abilities)

**Comment by Jerrythemagicdog** [comment]
This is a test with ~130 attacks against a boss level dummy (which means 1.8% less crit chance https://github.com/SunstriderEmu/BugTracker/issues/1530). Please use a bigger sample size if you're looking to confirm something doesn't work, thanks.

**Comment by TheMoneyHater** [comment]
Jerry, where did u get those values from? the 4.8% and 1.8%. It says on the wiki its -3%? or am I missing something?

**Comment by Jerrythemagicdog** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/1530

**Comment by kelno** [comment]
Thanks for reporting!
So I checked and this seems to work as expected, and I have exactly 3.2% crit chance by default, which matches the expected value of 5% - 1.8%.
This is due to crit suppression as talked about in the issue that Jerry linked.
Note that pets are considered like NPCs right now rather than considered like players. Players only suffer 0.6% reduction.
We're not sure what's correct here but for now I'm changing this so that every pets are considered like players for this purpose.

https://github.com/kelno/sunstrider/commit/d3b90d8f51fbdaf0e53372f46e722cd1765b1841
(applied on next server update)
