### ISSUE TITLE
Trees are not providing LoS cover

### ISSUE THREAD

**Issue by Rayzeh** [SunstriderEmu/BugTracker#3944]
**Describe the bug**
Target line of sight is not working because people can cast through units like mountains,trees and it's kinda bad.For example i was low hp and i tried to drink water in battleground behind a tree in warsong and i got killed through that unit.

**To Reproduce**
1. I was doing quests in Shadowmoon Valley and one shaman started attacking me through one big stone , i didn't see him because the range was really big and i didn't know what killed me. Things like this ruins the game experience...
2.
3. 

**Expected behavior**
I hope this bug will be fixed and the game will be more enjoynable because people who care about pvp needs this thing to work correctly not only in the arena.

**Screenshots/videos**
Don't have any ss for this one but the bug its obvious,you can cast through any unit standing in front of you.

**Comment by Jerrythemagicdog** [comment]
This is not a bug, trees are not supposed to provide LoS in the open world, it's a custom change some vanilla servers did with the extent of even road signs providing line of sight.
What you're asking for is not a fix for a bug but a feature.

**Comment by Rayzeh** [comment]
But how about mountains?

**Comment by Rayzeh** [comment]
And the thing with trees happened in the battleground which is a very important thing like LoS to work .

**Comment by XepppX** [comment]
This ain't normal at all indeed.
Though i played on several tbc servers and on some of them you were able to LoS envoirement and on some other servers not.
What i learned out of it is that caster classes are so more powerfull on such a server due to the fact that
mellee classes will have the most rediculess hard time's to get to you since they need to run around envoirement while you can just cast true it.
O.p. for druids who can keep shifting out of cc around envoirement while casting true it.
Mellee shammy's can only shock while moving around the envoirement.
warriors are worth nothing in this case.
Pala's and rogue's need to use all there cd's in order to being a good player while you play just one handed eazy mode.
So if you can't LoS a fight you need to outrange it....
Mellee classes waiting for you to come after them after a corner won't happen here they just got shot if it's not a building.

**Comment by kelno** [comment]
This was changed from WotLK, before that many models don't provide LoS. This core even DID provide LoS from trees before but that was reverted because not correct for TBC.
We're not closed to this but this is a custom change to be discussed.

**Comment by kelno** [comment]
We'll keep it TBC like for now.
