### ISSUE TITLE
(Dungeon) Dire Maul North Tribute run is not working (buffs)

### ISSUE THREAD

**Issue by Ticketdudu** [SunstriderEmu/BugTracker#4072]
The Dire Maul (North) is not working properly, if u kill the endboss, no ogre is spawning. Usually there spawns an ogre that u have to talk to to get a buff that makes u friendly to all the ogres in the dungeon. On this way u can walk back to the other bosses and get a buff from them.

How to reproduce:
1. Enter Dire Maul North
2. Skip all bosses (pref. in stealth)
3. Kill the endboss
If u did that, an ogre should spawn that u have to talk to, but he isnt spawning.

Clip:
https://drive.google.com/file/d/1w5xdmkuBdRAHOjFMIhRBto62NxbcPKYZ/view?usp=sharing

I hope it will get fixed so players can get the kinda decent tribute run buffs :)

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with next update.
Tribute run buffs won't be available for players above level 63 though, as per 2.1 patch notes:
""Fengus' Ferocity, Mol'dar's Moxie, Inv misc head dragon 01 [[Rallying Cry of the Dragonslayer]](https://wowpedia.fandom.com/wiki/Rallying_Cry_of_the_Dragonslayer), Slip'kik's Savvy and Ability creature poison 05 [[Spirit of Zandalar]](https://wowpedia.fandom.com/wiki/Spirit_of_Zandalar) these buffs will no longer work on targets over level 63.""
