### ISSUE TITLE
Low-Mid Level Herbs

### ISSUE THREAD

**Issue by Kehless** [SunstriderEmu/BugTracker#4084]
For people trying to level Herbalism, there are hardly any herbs in these low-mid level zones. Please help. I'm sure I'm not the only one who's having trouble.

**Comment by Kehless** [comment]
For people trying to level Herbalism, there are hardly any herbs in these low-mid level zones. Please help. I'm sure I'm not the only one who's having trouble.

**Comment by Massie323** [comment]
It's not that there aren't **_any_** nodes in the zone, but rather that some zones seem to be pseudo-bugged and have like 12 nodes spawned within a small area. Loch Modan for example has barely any nodes on the western side which should spawn Peaceblooms/Silverleaves/Mageroyales, but that's because the small islands in the middle have about 12 Silverleaf nodes active, hogging the node-limit and since no one ever goes to those islands to level, it appears like no low-nodes exist elsewhere.

Leveling Herbalism isn't that much of a struggle though, you just need to know the hotspots for this server's database (i.e. the Silverleaves on the Loch Modan isles, or that Bruiseweed grows near buildings in Westfall). Additionally, always shift-loot the node until you get the skillup. You can repeatedly herb (and mine) a node even if it's green until you get the skillup.

**Comment by z5n** [comment]
issue has since been fixed
