### ISSUE TITLE
Ring of Blood unavailable

### ISSUE THREAD

**Issue by esscoot** [SunstriderEmu/BugTracker#4300]
Ring of Blood quests are unavailable as the questgiver (Gurgthock) appears to be in an event, but no mobs in the arena are present. Upon interaction he says they are in the middle of a battle, but no battle is present.

**Comment by tankfest** [comment]
i just did ring of blood yesterday, we only encountered one glitch that might be related to this:
when we lost to the warmaul champion, our quest logs didn't mark the quest as failed like it should have, so we all dropped the quest to ensure it didn't bug out or anything, and so that we could start the event again.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, we've found some more cases where the event may fail to reset and fixed them. If there are still problems with the quest please let us know, thanks.
