### ISSUE TITLE
Escorts: creature WALKS back to the last point after the engagement and assists other far away players on their way back

### ISSUE THREAD

**Issue by tankfest** [SunstriderEmu/BugTracker#4385]

**Comment by Massie323** [comment]
I would like to add to this another issue that double-dips into this one; escort mobs have an insanely high "assist" range where they will help the player if they are in combat. However aside from the huge range (which may be intentional), they are also assisting any other player that is in combat within ~45yards, or in other words, they will react to any in-combat hostile mob within that range. This combined with the slow backtracking means that it essentially leads into an impossible chain of the mob being pulled away by "nearby" combat and not reaching its original position fast enough to make any progress.

**Comment by Jerrythemagicdog** [comment]
Walking back fixed with https://github.com/kelno/sunstrider/commit/d432415e918dce9e3450d8b012f033d17bfc5b26
the second part does sound incredibly annoying yes

**Comment by Jerrythemagicdog** [comment]
Fixed with next update
