### ISSUE TITLE
[#158] Various NPCs in Shadowmoon Valley not fighting

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#459]
<a href="https://github.com/artieau"><img src="https://avatars0.githubusercontent.com/u/40563134?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [artieau](https://github.com/artieau)**
_Saturday Jan 12, 2019 at 07:08 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/158_

----

In Shadowmoon Valley outside Wildhammer Stronghold, there are Infernal Attacker which stand next to Wildhammer Defender.

The Mobs should attack each other.
More Infernal Attacker should spawn (similar to outside Thrallmar in HFP).

![image](https://user-images.githubusercontent.com/40563134/51070417-f309fe00-1694-11e9-992c-69fb77a3f7bc.png)
Infernal -
![image](https://user-images.githubusercontent.com/40563134/51070430-0cab4580-1695-11e9-8ad7-777501ab35a3.png)

**Comment by Jerrythemagicdog** [comment]
fixed in https://github.com/kelno/sunstrider-scripts/commit/1d7d2d5d3f47519164bfd799cddd4f7cfd84d3c0

Only one problem remains - sometimes the infernal stands there and waits for something without engaging until the units he's supposed to attack move (they're in combat with the other Infernal at the time that's why it looks weird.)
