### ISSUE TITLE
[#229] Gathering nodes spawning on top of each other

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#508]
<a href="https://github.com/BrockSamson1"><img src="https://avatars3.githubusercontent.com/u/46757539?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [BrockSamson1](https://github.com/BrockSamson1)**
_Tuesday Jan 29, 2019 at 08:17 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/229_

----

2 nodes are often in the same location. observed with both mining and herbing. Always two different types of nodes ie. khorium and fel iron.

**Current behaviour:**

As in screenshot a node of ragveil and a node of flamecap are both spawned in the same place.

**Expected behaviour:**

Nodes locations should only have one spawn at a time

**Steps to reproduce the problem:**

1. Search for nodes
2. Observe more than one.

**rev. hash/commit:** 
In screenshot
![double nodes](https://user-images.githubusercontent.com/46757539/51893911-70a26d80-23fa-11e9-96bc-0a58055835c9.jpg)

**Comment by kakarotkaruma** [comment]
Also had this issue.

**Comment by kelno** [comment]
To dev:
This should be checked with db queries rather than doing it per case

**Comment by artieau** [comment]
It seems many spawns are just on their own merit, rather than how db should handle this.
As in, it seems possible for every available spawn point to be up at the same time
Pic below is a small area near the dark portal tracking Mining nodes - its way too high, this is replicated over the whole world server.
![image](https://user-images.githubusercontent.com/40563134/54471605-b206a500-480f-11e9-82a2-3e3d23b18400.png)
