### ISSUE TITLE
[#279] Prayer of Mending attributes threat to priest

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/BugTracker#548]
<a href="https://github.com/Desparto"><img src="https://avatars0.githubusercontent.com/u/26176852?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Desparto](https://github.com/Desparto)**
_Thursday Feb 07, 2019 at 12:11 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/279_

----

**Current behaviour:**

Prayer of Mending spell attributes it's threat to the casting priest when the target takes damage and PoM heals.

**Expected behaviour:**

This threat is supposed to be considered a "selfheal" of the target, and should attribute its healing threat to the target it is currently cast on.

**Steps to reproduce the problem:**

1. Cast PoM on a target (e.g. tank in dungeon)
2. Target runs to target and doesn't cast any spells, aggroing mob but not generating any threat. 
3. Target takes damage leading PoM to proc and target to heal. Mobs will run to priest, where as this threat should be given to the target instead.

Reference information: Prayer of Mending: when Prayer of Mending procs (i.e. dmg taken, PoM charge gets used up), the threat from the healing done is attributed directly to the person being healed. This is incredibly useful for tank threat, as you can put PoM and a PW:S up on a tank just before the pull, and instantly refresh the PoM when the first charge is used up for an easy 2k+ threat for your tank. This is enough to land a 4k heal without pulling aggro: very useful for heroics where you have no salv and no CC.

http://web.archive.org/web/20080913120601/http://elitistjerks.com:80/f31/t23790-priest_holy_raiding_compendium_v2_wow-2_4_3_a/

Revision 10392

**Comment by kelno** [comment]
<a href="https://github.com/artieau"><img src="https://avatars0.githubusercontent.com/u/40563134?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [artieau](https://github.com/artieau)**
_Thursday Feb 07, 2019 at 12:57 GMT_

----

Shaman spell Earth Shield is also showing this effect - believe it to be incorrect too, but will find a source and new ticket if so,

**Comment by Harrock1** [comment]
Still occuring (re Earth Shield threat)

**Comment by Gredsta** [comment]
Still occurring (Priest)

Gets me killed constantly, can't break the habit of pre casting on tank.

**Comment by Harrock1** [comment]
Still occuring

**Comment by Gredsta** [comment]
Still occurring - this is beginning to become quite a large issue particularly in light of the Paladin Ret aura hotfix. They no longer have that crutch to make up for the lost threat of a PoM on pull, which was standard practice during retail. Because of this, tanks are having less instant threat on pull and it is more painful than needed trying to manage threat particularly in heroic dungeons where tank damage is high and you can't wait to begin healing. In addition, during AoE damage, due to priests now obtaining significant gear, if we get a 5 bounce we have unrealistic threat. This is most notable on Curator, where as a Holy Priest I consistently sit second on threat, even after an evocate and warlocks doing significant damage. This creates a lot of flow on issues.

I understand in the grand scheme this is fairly low priority, but it is becoming a serious issue for holy priests.

**Comment by Harrock1** [comment]
Its very hard to tank mobs when you have shaman/priest heals as a warrior gred. Love wasting intervene in 3 sec of pull

**Comment by kelno** [comment]
Fixed with 11036

**Comment by artieau** [comment]
@kelno  Re-opening to review this as players report the issue has returned. Possible regression

**Comment by kelno** [comment]
Tested again now, it works
